// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ApiMeta = {
    code: number;
    message: string;
    time: string;
};

export type App = {
    id: string;
    name: string;
    desc: string;
    icon: string;
    badge?: string | null;
    color: string;
    status: 'enabled' | 'draft' | 'paused';
    createdAt: string;
    owner: string;
    records: number;
};

export type FormSummary = {
    id: string;
    name: string;
    category: string;
    count?: number | null;
    status: string;
    latestSchemaVersion: number;
    createdAt: string;
};

export type NavigationItem = {
    id: string;
    itemType: 'form' | 'system' | 'group' | 'link';
    targetFormUuid?: string | null;
    title: string;
    pathSlug: string;
    sortOrder: number;
    isDefaultEntry: boolean;
    parentId?: string | null;
    visibilityRule?: string | null;
};

export type SchemaPayload = {
    formUuid: string;
    schema: {
        [key: string]: unknown;
    };
    version: number;
    draftVersion: number;
    publishedVersion: number;
    latestVersion: number;
    published: boolean;
};

export type FormRecord = {
    id: string;
    formUuid: string;
    schemaVersion: number;
    data: {
        [key: string]: unknown;
    };
    createdBy: string;
    updatedBy: string;
    createdAt: string;
    updatedAt: string;
};

export type FormRecordList = {
    items: Array<FormRecord>;
    total: number;
};

export type AutomationFlow = {
    id: string;
    appId: string;
    name: string;
    description?: string | null;
    status: 'enabled' | 'paused' | 'draft';
    currentVersion: number;
    triggerFormUuid?: string | null;
    triggerEvent: 'before_create' | 'after_create' | 'before_update' | 'after_update' | 'before_delete' | 'after_delete';
    triggerLabel: string;
    nodesCount: number;
    createdBy: string;
    updatedBy: string;
    createdAt: string;
    updatedAt: string;
};

export type AutomationFlowList = {
    items: Array<AutomationFlow>;
    total: number;
    enabled: number;
    paused: number;
    draft: number;
};

export type AutomationFlowDetail = {
    id: string;
    appId: string;
    name: string;
    description?: string | null;
    status: 'enabled' | 'paused' | 'draft';
    currentVersion: number;
    triggerFormUuid?: string | null;
    triggerEvent: 'before_create' | 'after_create' | 'before_update' | 'after_update' | 'before_delete' | 'after_delete';
    triggerLabel: string;
    triggerConfig: {
        [key: string]: unknown;
    };
    nodes: Array<{
        [key: string]: unknown;
    }>;
    edges: Array<{
        [key: string]: unknown;
    }>;
    nodesCount: number;
    createdBy: string;
    updatedBy: string;
    createdAt: string;
    updatedAt: string;
};

export type FormVersionSummary = {
    version: number;
    published: boolean;
    isCurrentDraft: boolean;
    isCurrentPublished: boolean;
    changeLog?: string | null;
    createdAt: string;
};

export type AutomationFlowVersionSummary = {
    version: number;
    name: string;
    status: 'enabled' | 'paused' | 'draft';
    createdBy: string;
    createdAt: string;
    changeSummary?: string | null;
};

export type CreateAppRequest = {
    name?: string;
    owner?: string;
};

export type UpdateAppRequest = {
    name?: string;
    status?: 'enabled' | 'paused';
};

export type SaveSchemaRequest = {
    schema: {
        [key: string]: unknown;
    };
    change_log?: string;
};

export type RestoreVersionRequest = {
    change_log?: string;
};

export type CreateFormRecordRequest = {
    data: {
        [key: string]: unknown;
    };
    operator?: string;
};

export type UpdateFormRecordRequest = {
    data: {
        [key: string]: unknown;
    };
    operator?: string;
};

export type CreateAutomationFlowRequest = {
    name?: string;
    description?: string;
    triggerFormUuid?: string;
    triggerEvent?: 'before_create' | 'after_create' | 'before_update' | 'after_update' | 'before_delete' | 'after_delete';
    operator?: string;
};

export type UpdateAutomationFlowRequest = {
    name?: string;
    description?: string;
    status?: 'enabled' | 'paused' | 'draft';
    triggerFormUuid?: string;
    triggerEvent?: 'before_create' | 'after_create' | 'before_update' | 'after_update' | 'before_delete' | 'after_delete';
    triggerConfig?: {
        [key: string]: unknown;
    };
    nodes?: Array<{
        [key: string]: unknown;
    }>;
    edges?: Array<{
        [key: string]: unknown;
    }>;
    changeSummary?: string;
    operator?: string;
};

export type AppResponse = ApiMeta & {
    data: App;
};

export type AppListResponse = ApiMeta & {
    data: Array<App>;
};

export type FormResponse = ApiMeta & {
    data: FormSummary;
};

export type FormListResponse = ApiMeta & {
    data: Array<FormSummary>;
};

export type NavigationListResponse = ApiMeta & {
    data: Array<NavigationItem>;
};

export type FormSchemaResponse = ApiMeta & {
    data: SchemaPayload;
};

export type FormRecordResponse = ApiMeta & {
    data: FormRecord;
};

export type FormRecordListResponse = ApiMeta & {
    data: FormRecordList;
};

export type AutomationFlowResponse = ApiMeta & {
    data: AutomationFlow;
};

export type AutomationFlowListResponse = ApiMeta & {
    data: AutomationFlowList;
};

export type AutomationFlowDetailResponse = ApiMeta & {
    data: AutomationFlowDetail;
};

export type AutomationFlowVersionListResponse = ApiMeta & {
    data: Array<AutomationFlowVersionSummary>;
};

export type GenericSuccessResponse = ApiMeta & {
    data: {
        [key: string]: unknown;
    };
};

export type FormVersionListResponse = ApiMeta & {
    data: Array<FormVersionSummary>;
};

export type ErrorResponse = ApiMeta & {
    data: null;
};

export type ListAppsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/apps';
};

export type ListAppsErrors = {
    /**
     * Backend error
     */
    500: ErrorResponse;
    /**
     * Backend unavailable
     */
    503: ErrorResponse;
};

export type ListAppsError = ListAppsErrors[keyof ListAppsErrors];

export type ListAppsResponses = {
    /**
     * Wrapped app list
     */
    200: AppListResponse;
};

export type ListAppsResponse = ListAppsResponses[keyof ListAppsResponses];

export type CreateAppData = {
    body?: CreateAppRequest;
    path?: never;
    query?: never;
    url: '/api/apps';
};

export type CreateAppErrors = {
    /**
     * Backend error
     */
    500: ErrorResponse;
    /**
     * Backend unavailable
     */
    503: ErrorResponse;
};

export type CreateAppError = CreateAppErrors[keyof CreateAppErrors];

export type CreateAppResponses = {
    /**
     * Wrapped created app
     */
    201: AppResponse;
};

export type CreateAppResponse = CreateAppResponses[keyof CreateAppResponses];

export type DeleteAppData = {
    body?: never;
    path: {
        appId: string;
    };
    query?: never;
    url: '/api/apps/{appId}';
};

export type DeleteAppErrors = {
    /**
     * App not found
     */
    404: ErrorResponse;
};

export type DeleteAppError = DeleteAppErrors[keyof DeleteAppErrors];

export type DeleteAppResponses = {
    /**
     * Wrapped delete result
     */
    200: GenericSuccessResponse;
};

export type DeleteAppResponse = DeleteAppResponses[keyof DeleteAppResponses];

export type UpdateAppData = {
    body: UpdateAppRequest;
    path: {
        appId: string;
    };
    query?: never;
    url: '/api/apps/{appId}';
};

export type UpdateAppErrors = {
    /**
     * App not found
     */
    404: ErrorResponse;
};

export type UpdateAppError = UpdateAppErrors[keyof UpdateAppErrors];

export type UpdateAppResponses = {
    /**
     * Wrapped updated app
     */
    200: AppResponse;
};

export type UpdateAppResponse = UpdateAppResponses[keyof UpdateAppResponses];

export type ListAppNavigationData = {
    body?: never;
    path: {
        appId: string;
    };
    query?: never;
    url: '/api/apps/{appId}/navigation';
};

export type ListAppNavigationErrors = {
    /**
     * Backend error
     */
    500: ErrorResponse;
    /**
     * Backend unavailable
     */
    503: ErrorResponse;
};

export type ListAppNavigationError = ListAppNavigationErrors[keyof ListAppNavigationErrors];

export type ListAppNavigationResponses = {
    /**
     * Wrapped navigation item list
     */
    200: NavigationListResponse;
};

export type ListAppNavigationResponse = ListAppNavigationResponses[keyof ListAppNavigationResponses];

export type ListFormsData = {
    body?: never;
    path: {
        appId: string;
    };
    query?: never;
    url: '/api/apps/{appId}/forms';
};

export type ListFormsErrors = {
    /**
     * Backend error
     */
    500: ErrorResponse;
    /**
     * Backend unavailable
     */
    503: ErrorResponse;
};

export type ListFormsError = ListFormsErrors[keyof ListFormsErrors];

export type ListFormsResponses = {
    /**
     * Wrapped form list
     */
    200: FormListResponse;
};

export type ListFormsResponse = ListFormsResponses[keyof ListFormsResponses];

export type CreateFormData = {
    body?: never;
    path: {
        appId: string;
    };
    query?: never;
    url: '/api/apps/{appId}/forms';
};

export type CreateFormErrors = {
    /**
     * Backend error
     */
    500: ErrorResponse;
    /**
     * Backend unavailable
     */
    503: ErrorResponse;
};

export type CreateFormError = CreateFormErrors[keyof CreateFormErrors];

export type CreateFormResponses = {
    /**
     * Wrapped created form
     */
    201: FormResponse;
};

export type CreateFormResponse = CreateFormResponses[keyof CreateFormResponses];

export type ListAutomationFlowsData = {
    body?: never;
    path: {
        appId: string;
    };
    query?: never;
    url: '/api/apps/{appId}/automations';
};

export type ListAutomationFlowsErrors = {
    /**
     * Backend error
     */
    500: ErrorResponse;
    /**
     * Backend unavailable
     */
    503: ErrorResponse;
};

export type ListAutomationFlowsError = ListAutomationFlowsErrors[keyof ListAutomationFlowsErrors];

export type ListAutomationFlowsResponses = {
    /**
     * Wrapped automation flow list
     */
    200: AutomationFlowListResponse;
};

export type ListAutomationFlowsResponse = ListAutomationFlowsResponses[keyof ListAutomationFlowsResponses];

export type CreateAutomationFlowData = {
    body?: CreateAutomationFlowRequest;
    path: {
        appId: string;
    };
    query?: never;
    url: '/api/apps/{appId}/automations';
};

export type CreateAutomationFlowErrors = {
    /**
     * Invalid automation configuration
     */
    400: ErrorResponse;
    /**
     * Backend error
     */
    500: ErrorResponse;
    /**
     * Backend unavailable
     */
    503: ErrorResponse;
};

export type CreateAutomationFlowError = CreateAutomationFlowErrors[keyof CreateAutomationFlowErrors];

export type CreateAutomationFlowResponses = {
    /**
     * Wrapped created automation flow
     */
    201: AutomationFlowResponse;
};

export type CreateAutomationFlowResponse = CreateAutomationFlowResponses[keyof CreateAutomationFlowResponses];

export type DeleteAutomationFlowData = {
    body?: never;
    path: {
        automationId: string;
    };
    query?: never;
    url: '/api/automations/{automationId}';
};

export type DeleteAutomationFlowErrors = {
    /**
     * Automation flow not found
     */
    404: ErrorResponse;
};

export type DeleteAutomationFlowError = DeleteAutomationFlowErrors[keyof DeleteAutomationFlowErrors];

export type DeleteAutomationFlowResponses = {
    /**
     * Wrapped delete result
     */
    200: GenericSuccessResponse;
};

export type DeleteAutomationFlowResponse = DeleteAutomationFlowResponses[keyof DeleteAutomationFlowResponses];

export type GetAutomationFlowData = {
    body?: never;
    path: {
        automationId: string;
    };
    query?: never;
    url: '/api/automations/{automationId}';
};

export type GetAutomationFlowErrors = {
    /**
     * Automation flow not found
     */
    404: ErrorResponse;
};

export type GetAutomationFlowError = GetAutomationFlowErrors[keyof GetAutomationFlowErrors];

export type GetAutomationFlowResponses = {
    /**
     * Wrapped automation flow detail
     */
    200: AutomationFlowDetailResponse;
};

export type GetAutomationFlowResponse = GetAutomationFlowResponses[keyof GetAutomationFlowResponses];

export type UpdateAutomationFlowData = {
    body: UpdateAutomationFlowRequest;
    path: {
        automationId: string;
    };
    query?: never;
    url: '/api/automations/{automationId}';
};

export type UpdateAutomationFlowErrors = {
    /**
     * Invalid automation configuration
     */
    400: ErrorResponse;
    /**
     * Automation flow not found
     */
    404: ErrorResponse;
};

export type UpdateAutomationFlowError = UpdateAutomationFlowErrors[keyof UpdateAutomationFlowErrors];

export type UpdateAutomationFlowResponses = {
    /**
     * Wrapped updated automation flow
     */
    200: AutomationFlowResponse;
};

export type UpdateAutomationFlowResponse = UpdateAutomationFlowResponses[keyof UpdateAutomationFlowResponses];

export type ListAutomationFlowVersionsData = {
    body?: never;
    path: {
        automationId: string;
    };
    query?: never;
    url: '/api/automations/{automationId}/versions';
};

export type ListAutomationFlowVersionsErrors = {
    /**
     * Automation flow not found
     */
    404: ErrorResponse;
};

export type ListAutomationFlowVersionsError = ListAutomationFlowVersionsErrors[keyof ListAutomationFlowVersionsErrors];

export type ListAutomationFlowVersionsResponses = {
    /**
     * Wrapped automation version list
     */
    200: AutomationFlowVersionListResponse;
};

export type ListAutomationFlowVersionsResponse = ListAutomationFlowVersionsResponses[keyof ListAutomationFlowVersionsResponses];

export type GetFormSchemaData = {
    body?: never;
    path: {
        formUuid: string;
    };
    query?: {
        scope?: 'draft' | 'published' | 'latest';
        version?: number;
    };
    url: '/api/forms/{formUuid}/schema';
};

export type GetFormSchemaErrors = {
    /**
     * Schema not found
     */
    404: ErrorResponse;
    /**
     * Backend unavailable
     */
    503: ErrorResponse;
};

export type GetFormSchemaError = GetFormSchemaErrors[keyof GetFormSchemaErrors];

export type GetFormSchemaResponses = {
    /**
     * Wrapped schema
     */
    200: FormSchemaResponse;
};

export type GetFormSchemaResponse = GetFormSchemaResponses[keyof GetFormSchemaResponses];

export type ListFormRecordsData = {
    body?: never;
    path: {
        formUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/records';
};

export type ListFormRecordsErrors = {
    /**
     * Form not found
     */
    404: ErrorResponse;
};

export type ListFormRecordsError = ListFormRecordsErrors[keyof ListFormRecordsErrors];

export type ListFormRecordsResponses = {
    /**
     * Wrapped form records
     */
    200: FormRecordListResponse;
};

export type ListFormRecordsResponse = ListFormRecordsResponses[keyof ListFormRecordsResponses];

export type CreateFormRecordData = {
    body: CreateFormRecordRequest;
    path: {
        formUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/records';
};

export type CreateFormRecordErrors = {
    /**
     * Form not found
     */
    404: ErrorResponse;
};

export type CreateFormRecordError = CreateFormRecordErrors[keyof CreateFormRecordErrors];

export type CreateFormRecordResponses = {
    /**
     * Wrapped created form record
     */
    201: FormRecordResponse;
};

export type CreateFormRecordResponse = CreateFormRecordResponses[keyof CreateFormRecordResponses];

export type DeleteFormRecordData = {
    body?: never;
    path: {
        formUuid: string;
        recordUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/records/{recordUuid}';
};

export type DeleteFormRecordErrors = {
    /**
     * Form or record not found
     */
    404: ErrorResponse;
};

export type DeleteFormRecordError = DeleteFormRecordErrors[keyof DeleteFormRecordErrors];

export type DeleteFormRecordResponses = {
    /**
     * Wrapped delete result
     */
    200: GenericSuccessResponse;
};

export type DeleteFormRecordResponse = DeleteFormRecordResponses[keyof DeleteFormRecordResponses];

export type UpdateFormRecordData = {
    body: UpdateFormRecordRequest;
    path: {
        formUuid: string;
        recordUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/records/{recordUuid}';
};

export type UpdateFormRecordErrors = {
    /**
     * Form or record not found
     */
    404: ErrorResponse;
};

export type UpdateFormRecordError = UpdateFormRecordErrors[keyof UpdateFormRecordErrors];

export type UpdateFormRecordResponses = {
    /**
     * Wrapped updated form record
     */
    200: FormRecordResponse;
};

export type UpdateFormRecordResponse = UpdateFormRecordResponses[keyof UpdateFormRecordResponses];

export type ListFormVersionsData = {
    body?: never;
    path: {
        formUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/versions';
};

export type ListFormVersionsErrors = {
    /**
     * Form not found
     */
    404: ErrorResponse;
    /**
     * Backend unavailable
     */
    503: ErrorResponse;
};

export type ListFormVersionsError = ListFormVersionsErrors[keyof ListFormVersionsErrors];

export type ListFormVersionsResponses = {
    /**
     * Wrapped version list
     */
    200: FormVersionListResponse;
};

export type ListFormVersionsResponse = ListFormVersionsResponses[keyof ListFormVersionsResponses];

export type GetFormVersionData = {
    body?: never;
    path: {
        formUuid: string;
        version: number;
    };
    query?: never;
    url: '/api/forms/{formUuid}/versions/{version}';
};

export type GetFormVersionErrors = {
    /**
     * Schema not found
     */
    404: ErrorResponse;
};

export type GetFormVersionError = GetFormVersionErrors[keyof GetFormVersionErrors];

export type GetFormVersionResponses = {
    /**
     * Wrapped schema
     */
    200: FormSchemaResponse;
};

export type GetFormVersionResponse = GetFormVersionResponses[keyof GetFormVersionResponses];

export type PublishFormSchemaData = {
    body?: never;
    path: {
        formUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/publish';
};

export type PublishFormSchemaErrors = {
    /**
     * Form not found
     */
    404: ErrorResponse;
};

export type PublishFormSchemaError = PublishFormSchemaErrors[keyof PublishFormSchemaErrors];

export type PublishFormSchemaResponses = {
    /**
     * Wrapped published schema
     */
    200: FormSchemaResponse;
};

export type PublishFormSchemaResponse = PublishFormSchemaResponses[keyof PublishFormSchemaResponses];

export type RestoreFormVersionData = {
    body?: RestoreVersionRequest;
    path: {
        formUuid: string;
        version: number;
    };
    query?: never;
    url: '/api/forms/{formUuid}/versions/{version}/restore';
};

export type RestoreFormVersionErrors = {
    /**
     * Version not found
     */
    404: ErrorResponse;
};

export type RestoreFormVersionError = RestoreFormVersionErrors[keyof RestoreFormVersionErrors];

export type RestoreFormVersionResponses = {
    /**
     * Wrapped restored schema
     */
    200: FormSchemaResponse;
};

export type RestoreFormVersionResponse = RestoreFormVersionResponses[keyof RestoreFormVersionResponses];

export type SaveFormSchemaDraftData = {
    body: SaveSchemaRequest;
    path: {
        formUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/schema/draft';
};

export type SaveFormSchemaDraftErrors = {
    /**
     * Form not found
     */
    404: ErrorResponse;
    /**
     * Backend unavailable
     */
    503: ErrorResponse;
};

export type SaveFormSchemaDraftError = SaveFormSchemaDraftErrors[keyof SaveFormSchemaDraftErrors];

export type SaveFormSchemaDraftResponses = {
    /**
     * Wrapped saved schema
     */
    200: FormSchemaResponse;
};

export type SaveFormSchemaDraftResponse = SaveFormSchemaDraftResponses[keyof SaveFormSchemaDraftResponses];
