// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateAppData, CreateAppErrors, CreateAppResponses, CreateAutomationFlowData, CreateAutomationFlowErrors, CreateAutomationFlowResponses, CreateFormData, CreateFormErrors, CreateFormRecordData, CreateFormRecordErrors, CreateFormRecordResponses, CreateFormResponses, DeleteAppData, DeleteAppErrors, DeleteAppResponses, DeleteAutomationFlowData, DeleteAutomationFlowErrors, DeleteAutomationFlowResponses, DeleteFormRecordData, DeleteFormRecordErrors, DeleteFormRecordResponses, GetAutomationFlowData, GetAutomationFlowErrors, GetAutomationFlowResponses, GetFormSchemaData, GetFormSchemaErrors, GetFormSchemaResponses, GetFormVersionData, GetFormVersionErrors, GetFormVersionResponses, ListAppNavigationData, ListAppNavigationErrors, ListAppNavigationResponses, ListAppsData, ListAppsErrors, ListAppsResponses, ListAutomationFlowsData, ListAutomationFlowsErrors, ListAutomationFlowsResponses, ListAutomationFlowVersionsData, ListAutomationFlowVersionsErrors, ListAutomationFlowVersionsResponses, ListFormRecordsData, ListFormRecordsErrors, ListFormRecordsResponses, ListFormsData, ListFormsErrors, ListFormsResponses, ListFormVersionsData, ListFormVersionsErrors, ListFormVersionsResponses, PublishFormSchemaData, PublishFormSchemaErrors, PublishFormSchemaResponses, RestoreFormVersionData, RestoreFormVersionErrors, RestoreFormVersionResponses, SaveFormSchemaDraftData, SaveFormSchemaDraftErrors, SaveFormSchemaDraftResponses, UpdateAppData, UpdateAppErrors, UpdateAppResponses, UpdateAutomationFlowData, UpdateAutomationFlowErrors, UpdateAutomationFlowResponses, UpdateFormRecordData, UpdateFormRecordErrors, UpdateFormRecordResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List apps
 */
export const listApps = <ThrowOnError extends boolean = false>(options?: Options<ListAppsData, ThrowOnError>): RequestResult<ListAppsResponses, ListAppsErrors, ThrowOnError> => (options?.client ?? client).get<ListAppsResponses, ListAppsErrors, ThrowOnError>({ url: '/api/apps', ...options });

/**
 * Create empty app
 */
export const createApp = <ThrowOnError extends boolean = false>(options?: Options<CreateAppData, ThrowOnError>): RequestResult<CreateAppResponses, CreateAppErrors, ThrowOnError> => (options?.client ?? client).post<CreateAppResponses, CreateAppErrors, ThrowOnError>({
    url: '/api/apps',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Delete app and related form data
 */
export const deleteApp = <ThrowOnError extends boolean = false>(options: Options<DeleteAppData, ThrowOnError>): RequestResult<DeleteAppResponses, DeleteAppErrors, ThrowOnError> => (options.client ?? client).delete<DeleteAppResponses, DeleteAppErrors, ThrowOnError>({ url: '/api/apps/{appId}', ...options });

/**
 * Update app name or status
 */
export const updateApp = <ThrowOnError extends boolean = false>(options: Options<UpdateAppData, ThrowOnError>): RequestResult<UpdateAppResponses, UpdateAppErrors, ThrowOnError> => (options.client ?? client).patch<UpdateAppResponses, UpdateAppErrors, ThrowOnError>({
    url: '/api/apps/{appId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List app navigation items
 */
export const listAppNavigation = <ThrowOnError extends boolean = false>(options: Options<ListAppNavigationData, ThrowOnError>): RequestResult<ListAppNavigationResponses, ListAppNavigationErrors, ThrowOnError> => (options.client ?? client).get<ListAppNavigationResponses, ListAppNavigationErrors, ThrowOnError>({ url: '/api/apps/{appId}/navigation', ...options });

/**
 * List forms by app
 */
export const listForms = <ThrowOnError extends boolean = false>(options: Options<ListFormsData, ThrowOnError>): RequestResult<ListFormsResponses, ListFormsErrors, ThrowOnError> => (options.client ?? client).get<ListFormsResponses, ListFormsErrors, ThrowOnError>({ url: '/api/apps/{appId}/forms', ...options });

/**
 * Create blank form
 */
export const createForm = <ThrowOnError extends boolean = false>(options: Options<CreateFormData, ThrowOnError>): RequestResult<CreateFormResponses, CreateFormErrors, ThrowOnError> => (options.client ?? client).post<CreateFormResponses, CreateFormErrors, ThrowOnError>({ url: '/api/apps/{appId}/forms', ...options });

/**
 * List automation flows by app
 */
export const listAutomationFlows = <ThrowOnError extends boolean = false>(options: Options<ListAutomationFlowsData, ThrowOnError>): RequestResult<ListAutomationFlowsResponses, ListAutomationFlowsErrors, ThrowOnError> => (options.client ?? client).get<ListAutomationFlowsResponses, ListAutomationFlowsErrors, ThrowOnError>({ url: '/api/apps/{appId}/automations', ...options });

/**
 * Create automation flow
 */
export const createAutomationFlow = <ThrowOnError extends boolean = false>(options: Options<CreateAutomationFlowData, ThrowOnError>): RequestResult<CreateAutomationFlowResponses, CreateAutomationFlowErrors, ThrowOnError> => (options.client ?? client).post<CreateAutomationFlowResponses, CreateAutomationFlowErrors, ThrowOnError>({
    url: '/api/apps/{appId}/automations',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete automation flow
 */
export const deleteAutomationFlow = <ThrowOnError extends boolean = false>(options: Options<DeleteAutomationFlowData, ThrowOnError>): RequestResult<DeleteAutomationFlowResponses, DeleteAutomationFlowErrors, ThrowOnError> => (options.client ?? client).delete<DeleteAutomationFlowResponses, DeleteAutomationFlowErrors, ThrowOnError>({ url: '/api/automations/{automationId}', ...options });

/**
 * Get automation flow detail
 */
export const getAutomationFlow = <ThrowOnError extends boolean = false>(options: Options<GetAutomationFlowData, ThrowOnError>): RequestResult<GetAutomationFlowResponses, GetAutomationFlowErrors, ThrowOnError> => (options.client ?? client).get<GetAutomationFlowResponses, GetAutomationFlowErrors, ThrowOnError>({ url: '/api/automations/{automationId}', ...options });

/**
 * Update automation flow
 */
export const updateAutomationFlow = <ThrowOnError extends boolean = false>(options: Options<UpdateAutomationFlowData, ThrowOnError>): RequestResult<UpdateAutomationFlowResponses, UpdateAutomationFlowErrors, ThrowOnError> => (options.client ?? client).patch<UpdateAutomationFlowResponses, UpdateAutomationFlowErrors, ThrowOnError>({
    url: '/api/automations/{automationId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List automation flow versions
 */
export const listAutomationFlowVersions = <ThrowOnError extends boolean = false>(options: Options<ListAutomationFlowVersionsData, ThrowOnError>): RequestResult<ListAutomationFlowVersionsResponses, ListAutomationFlowVersionsErrors, ThrowOnError> => (options.client ?? client).get<ListAutomationFlowVersionsResponses, ListAutomationFlowVersionsErrors, ThrowOnError>({ url: '/api/automations/{automationId}/versions', ...options });

/**
 * Get latest schema by form uuid
 */
export const getFormSchema = <ThrowOnError extends boolean = false>(options: Options<GetFormSchemaData, ThrowOnError>): RequestResult<GetFormSchemaResponses, GetFormSchemaErrors, ThrowOnError> => (options.client ?? client).get<GetFormSchemaResponses, GetFormSchemaErrors, ThrowOnError>({ url: '/api/forms/{formUuid}/schema', ...options });

/**
 * List form records
 */
export const listFormRecords = <ThrowOnError extends boolean = false>(options: Options<ListFormRecordsData, ThrowOnError>): RequestResult<ListFormRecordsResponses, ListFormRecordsErrors, ThrowOnError> => (options.client ?? client).get<ListFormRecordsResponses, ListFormRecordsErrors, ThrowOnError>({ url: '/api/forms/{formUuid}/records', ...options });

/**
 * Create form record
 */
export const createFormRecord = <ThrowOnError extends boolean = false>(options: Options<CreateFormRecordData, ThrowOnError>): RequestResult<CreateFormRecordResponses, CreateFormRecordErrors, ThrowOnError> => (options.client ?? client).post<CreateFormRecordResponses, CreateFormRecordErrors, ThrowOnError>({
    url: '/api/forms/{formUuid}/records',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete form record
 */
export const deleteFormRecord = <ThrowOnError extends boolean = false>(options: Options<DeleteFormRecordData, ThrowOnError>): RequestResult<DeleteFormRecordResponses, DeleteFormRecordErrors, ThrowOnError> => (options.client ?? client).delete<DeleteFormRecordResponses, DeleteFormRecordErrors, ThrowOnError>({ url: '/api/forms/{formUuid}/records/{recordUuid}', ...options });

/**
 * Update form record
 */
export const updateFormRecord = <ThrowOnError extends boolean = false>(options: Options<UpdateFormRecordData, ThrowOnError>): RequestResult<UpdateFormRecordResponses, UpdateFormRecordErrors, ThrowOnError> => (options.client ?? client).patch<UpdateFormRecordResponses, UpdateFormRecordErrors, ThrowOnError>({
    url: '/api/forms/{formUuid}/records/{recordUuid}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List form schema versions
 */
export const listFormVersions = <ThrowOnError extends boolean = false>(options: Options<ListFormVersionsData, ThrowOnError>): RequestResult<ListFormVersionsResponses, ListFormVersionsErrors, ThrowOnError> => (options.client ?? client).get<ListFormVersionsResponses, ListFormVersionsErrors, ThrowOnError>({ url: '/api/forms/{formUuid}/versions', ...options });

/**
 * Get specific form schema version
 */
export const getFormVersion = <ThrowOnError extends boolean = false>(options: Options<GetFormVersionData, ThrowOnError>): RequestResult<GetFormVersionResponses, GetFormVersionErrors, ThrowOnError> => (options.client ?? client).get<GetFormVersionResponses, GetFormVersionErrors, ThrowOnError>({ url: '/api/forms/{formUuid}/versions/{version}', ...options });

/**
 * Publish current draft schema
 */
export const publishFormSchema = <ThrowOnError extends boolean = false>(options: Options<PublishFormSchemaData, ThrowOnError>): RequestResult<PublishFormSchemaResponses, PublishFormSchemaErrors, ThrowOnError> => (options.client ?? client).post<PublishFormSchemaResponses, PublishFormSchemaErrors, ThrowOnError>({ url: '/api/forms/{formUuid}/publish', ...options });

/**
 * Restore historical version as new draft
 */
export const restoreFormVersion = <ThrowOnError extends boolean = false>(options: Options<RestoreFormVersionData, ThrowOnError>): RequestResult<RestoreFormVersionResponses, RestoreFormVersionErrors, ThrowOnError> => (options.client ?? client).post<RestoreFormVersionResponses, RestoreFormVersionErrors, ThrowOnError>({
    url: '/api/forms/{formUuid}/versions/{version}/restore',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Save form schema draft
 */
export const saveFormSchemaDraft = <ThrowOnError extends boolean = false>(options: Options<SaveFormSchemaDraftData, ThrowOnError>): RequestResult<SaveFormSchemaDraftResponses, SaveFormSchemaDraftErrors, ThrowOnError> => (options.client ?? client).post<SaveFormSchemaDraftResponses, SaveFormSchemaDraftErrors, ThrowOnError>({
    url: '/api/forms/{formUuid}/schema/draft',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
