// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AccessTokenResponse = {
    accessToken: string;
    expiresAt: string;
    expiresIn: number;
};

export type ActivatePlatformLicenseRequest = {
    license: string;
    licenseCenterUrl: string;
};

export type AgentKnowledgeBaseDefinition = {
    content?: string;
    description?: string;
    enabled: boolean;
    id: string;
    name: string;
    retrievalMode: string;
    sourceIds?: Array<string>;
};

export type AgentPageContext = {
    appId?: string | null;
    automationId?: string | null;
    businessId?: string | null;
    formDraftAssist?: boolean | null;
    formUuid?: string | null;
    route?: string | null;
};

export type AgentPluginDefinition = {
    description?: string;
    enabled: boolean;
    entrypoint?: string;
    id: string;
    manifestJson?: string;
    name: string;
    requiresConfirmation: boolean;
    version: string;
};

export type AiEmployeeMarketItem = {
    avatarUrl?: string | null;
    billingCycle: string;
    category: string;
    description: string;
    expiresAt?: number | null;
    id: string;
    installed: boolean;
    installedPackageVersion?: string | null;
    installedVersion?: string | null;
    latestPackageVersion: string;
    owned: boolean;
    priceCents: number;
    title: string;
    version: string;
};

export type ApiAgentSession = {
    agentId: string;
    appId?: string | null;
    context: unknown;
    createdAt: string;
    id: string;
    isPinned: boolean;
    modelProvider?: string | null;
    source: string;
    status: string;
    title: string;
    updatedAt: string;
};

export type ApiApp = {
    badge?: string | null;
    color: string;
    createdAt: string;
    deploymentType: string;
    desc: string;
    icon: string;
    id: string;
    name: string;
    onlineReleaseId?: string | null;
    onlineVersion?: string | null;
    owner: string;
    ownerAvatarUrl?: string | null;
    records: number;
};

export type ApiAppFieldOutline = {
    appId: string;
    appName: string;
    forms: Array<ApiFieldOutlineForm>;
};

export type ApiAutomationFlow = {
    appId: string;
    createdAt: string;
    createdBy: string;
    currentVersion: number;
    description?: string | null;
    flowType: AutomationFlowType;
    id: string;
    name: string;
    nodesCount: number;
    status: AutomationStatus;
    triggerEvent: AutomationTriggerEvent;
    triggerEvents: Array<AutomationTriggerEvent>;
    triggerFormUuid?: string | null;
    triggerLabel: string;
    updatedAt: string;
    updatedBy: string;
};

export type ApiAutomationFlowDetail = {
    appId: string;
    createdAt: string;
    createdBy: string;
    currentVersion: number;
    description?: string | null;
    edges: unknown;
    flowType: AutomationFlowType;
    id: string;
    name: string;
    nodes: unknown;
    nodesCount: number;
    status: AutomationStatus;
    triggerConfig: unknown;
    triggerEvent: AutomationTriggerEvent;
    triggerEvents: Array<AutomationTriggerEvent>;
    triggerFormUuid?: string | null;
    triggerLabel: string;
    updatedAt: string;
    updatedBy: string;
};

export type ApiAutomationFlowList = {
    draft: number;
    enabled: number;
    items: Array<ApiAutomationFlow>;
    paused: number;
    total: number;
};

export type ApiAutomationFlowVersionSummary = {
    changeSummary?: string | null;
    createdAt: string;
    createdBy: string;
    name: string;
    status: AutomationStatus;
    version: number;
};

export type ApiAutomationRun = {
    durationMs?: number | null;
    errorMessage?: string | null;
    finishedAt?: string | null;
    flowVersion: number;
    id: string;
    nodes: Array<ApiAutomationRunNode>;
    retryNodeKey?: string | null;
    retryRunUuid?: string | null;
    retrySource?: string | null;
    startedAt: string;
    status: string;
    triggerEvent: string;
    triggerPayload: unknown;
};

export type ApiAutomationRunNode = {
    durationMs?: number | null;
    errorMessage?: string | null;
    finishedAt?: string | null;
    id: string;
    input: unknown;
    nodeKey: string;
    nodeKind: string;
    nodeLabel: string;
    output?: unknown;
    startedAt: string;
    status: string;
};

export type ApiDetailForm = {
    detailFormUuid: string;
    primaryDisplayFieldId?: string | null;
    secondaryDisplayFieldId?: string | null;
    sourceFormUuid: string;
    subformFieldId: string;
    title: string;
};

export type ApiFieldOutlineField = {
    componentType: string;
    id: string;
    label: string;
    parentGroupId?: string | null;
};

export type ApiFieldOutlineForm = {
    compiledSchemaVersion?: number | null;
    fields: Array<ApiFieldOutlineField>;
    formType: FormType;
    formUuid: string;
    name: string;
    physicalTable?: string | null;
    schemaVersion: number;
    status: string;
};

export type ApiFormRecord = {
    createdAt: string;
    createdBy: string;
    createdByAvatarUrl?: string | null;
    createdByUserId?: string | null;
    data: unknown;
    formUuid: string;
    id: string;
    schemaVersion: number;
    submitterOrganization?: string | null;
    updatedAt: string;
    updatedBy: string;
};

export type ApiFormRecordList = {
    items: Array<ApiFormRecord>;
    page: number;
    pageSize: number;
    total: number;
};

export type ApiFormSummary = {
    category: string;
    count?: number | null;
    createdAt: string;
    formType: FormType;
    id: string;
    latestSchemaVersion: number;
    name: string;
    status: string;
};

export type ApiFormVersionSummary = {
    changeLog?: string | null;
    createdAt: string;
    version: number;
};

export type ApiNavigationItem = {
    id: string;
    isDefaultEntry: boolean;
    itemType: string;
    parentId?: string | null;
    pathSlug: string;
    sortOrder: number;
    targetFormUuid?: string | null;
    title: string;
    visibilityRule?: string | null;
};

export type ApiResponseAccessTokenResponse = {
    code: number;
    data?: {
        accessToken: string;
        expiresAt: string;
        expiresIn: number;
    };
    message: string;
    time: string;
};

export type ApiResponseAgentKnowledgeBaseDefinition = {
    code: number;
    data?: {
        content?: string;
        description?: string;
        enabled: boolean;
        id: string;
        name: string;
        retrievalMode: string;
        sourceIds?: Array<string>;
    };
    message: string;
    time: string;
};

export type ApiResponseAgentPluginDefinition = {
    code: number;
    data?: {
        description?: string;
        enabled: boolean;
        entrypoint?: string;
        id: string;
        manifestJson?: string;
        name: string;
        requiresConfirmation: boolean;
        version: string;
    };
    message: string;
    time: string;
};

export type ApiResponseApiAgentSession = {
    code: number;
    data?: {
        agentId: string;
        appId?: string | null;
        context: unknown;
        createdAt: string;
        id: string;
        isPinned: boolean;
        modelProvider?: string | null;
        source: string;
        status: string;
        title: string;
        updatedAt: string;
    };
    message: string;
    time: string;
};

export type ApiResponseApiApp = {
    code: number;
    data?: {
        badge?: string | null;
        color: string;
        createdAt: string;
        deploymentType: string;
        desc: string;
        icon: string;
        id: string;
        name: string;
        onlineReleaseId?: string | null;
        onlineVersion?: string | null;
        owner: string;
        ownerAvatarUrl?: string | null;
        records: number;
    };
    message: string;
    time: string;
};

export type ApiResponseApiAppFieldOutline = {
    code: number;
    data?: {
        appId: string;
        appName: string;
        forms: Array<ApiFieldOutlineForm>;
    };
    message: string;
    time: string;
};

export type ApiResponseApiAutomationFlow = {
    code: number;
    data?: {
        appId: string;
        createdAt: string;
        createdBy: string;
        currentVersion: number;
        description?: string | null;
        flowType: AutomationFlowType;
        id: string;
        name: string;
        nodesCount: number;
        status: AutomationStatus;
        triggerEvent: AutomationTriggerEvent;
        triggerEvents: Array<AutomationTriggerEvent>;
        triggerFormUuid?: string | null;
        triggerLabel: string;
        updatedAt: string;
        updatedBy: string;
    };
    message: string;
    time: string;
};

export type ApiResponseApiAutomationFlowDetail = {
    code: number;
    data?: {
        appId: string;
        createdAt: string;
        createdBy: string;
        currentVersion: number;
        description?: string | null;
        edges: unknown;
        flowType: AutomationFlowType;
        id: string;
        name: string;
        nodes: unknown;
        nodesCount: number;
        status: AutomationStatus;
        triggerConfig: unknown;
        triggerEvent: AutomationTriggerEvent;
        triggerEvents: Array<AutomationTriggerEvent>;
        triggerFormUuid?: string | null;
        triggerLabel: string;
        updatedAt: string;
        updatedBy: string;
    };
    message: string;
    time: string;
};

export type ApiResponseApiAutomationFlowList = {
    code: number;
    data?: {
        draft: number;
        enabled: number;
        items: Array<ApiAutomationFlow>;
        paused: number;
        total: number;
    };
    message: string;
    time: string;
};

export type ApiResponseApiDetailForm = {
    code: number;
    data?: {
        detailFormUuid: string;
        primaryDisplayFieldId?: string | null;
        secondaryDisplayFieldId?: string | null;
        sourceFormUuid: string;
        subformFieldId: string;
        title: string;
    };
    message: string;
    time: string;
};

export type ApiResponseApiFormRecord = {
    code: number;
    data?: {
        createdAt: string;
        createdBy: string;
        createdByAvatarUrl?: string | null;
        createdByUserId?: string | null;
        data: unknown;
        formUuid: string;
        id: string;
        schemaVersion: number;
        submitterOrganization?: string | null;
        updatedAt: string;
        updatedBy: string;
    };
    message: string;
    time: string;
};

export type ApiResponseApiFormRecordList = {
    code: number;
    data?: {
        items: Array<ApiFormRecord>;
        page: number;
        pageSize: number;
        total: number;
    };
    message: string;
    time: string;
};

export type ApiResponseApiFormSummary = {
    code: number;
    data?: {
        category: string;
        count?: number | null;
        createdAt: string;
        formType: FormType;
        id: string;
        latestSchemaVersion: number;
        name: string;
        status: string;
    };
    message: string;
    time: string;
};

export type ApiResponseApiNavigationItem = {
    code: number;
    data?: {
        id: string;
        isDefaultEntry: boolean;
        itemType: string;
        parentId?: string | null;
        pathSlug: string;
        sortOrder: number;
        targetFormUuid?: string | null;
        title: string;
        visibilityRule?: string | null;
    };
    message: string;
    time: string;
};

export type ApiResponseApiSchemaPayload = {
    code: number;
    data?: {
        formUuid: string;
        latestVersion: number;
        schema: unknown;
        version: number;
    };
    message: string;
    time: string;
};

export type ApiResponseClearDingTalkDataResponse = {
    code: number;
    data?: {
        deletedOrganizationUnits: number;
        deletedRolePermissions: number;
        deletedRoles: number;
        deletedUsers: number;
    };
    message: string;
    time: string;
};

export type ApiResponseCommunicationAvailabilityResponse = {
    code: number;
    data?: {
        enabled: boolean;
    };
    message: string;
    time: string;
};

export type ApiResponseCommunicationCleanupResponse = {
    code: number;
    data?: {
        deletedFiles: number;
        deletedMessages: number;
    };
    message: string;
    time: string;
};

export type ApiResponseCommunicationConversationResponse = {
    code: number;
    data?: {
        conversationType: string;
        id: string;
        lastMessageAt?: string | null;
        lastMessagePreview?: string | null;
        lastMessageSequence: number;
        members: Array<CommunicationMemberResponse>;
        title: string;
        unreadCount: number;
    };
    message: string;
    time: string;
};

export type ApiResponseCommunicationMessagePageResponse = {
    code: number;
    data?: {
        items: Array<CommunicationMessageResponse>;
        nextBeforeSequence?: number | null;
    };
    message: string;
    time: string;
};

export type ApiResponseCommunicationMessageResponse = {
    code: number;
    data?: {
        attachments: Array<CommunicationAttachmentResponse>;
        content: string;
        conversationId: string;
        createdAt: string;
        emailSubject?: string | null;
        fileIds: Array<string>;
        id: string;
        messageType: string;
        replacesMessageId?: string | null;
        senderUserId: string;
        sequence: number;
        status: string;
    };
    message: string;
    time: string;
};

export type ApiResponseCommunicationModuleSettings = {
    code: number;
    data?: {
        allowFileMessages?: boolean;
        allowedFileExtensions?: string;
        expiresAt?: number | null;
        installed?: boolean;
        licenseId?: string | null;
        maxFileUploadMb?: number;
        retentionDays?: number;
        websocketEnabled?: boolean;
    };
    message: string;
    time: string;
};

export type ApiResponseCommunicationStorageStatsResponse = {
    code: number;
    data?: {
        attachmentBytes: number;
        attachmentCount: number;
        conversationCount: number;
        messageBytes: number;
        messageCount: number;
        totalBytes: number;
    };
    message: string;
    time: string;
};

export type ApiResponseDatabaseConnectionTestResponse = {
    code: number;
    data?: {
        connected: boolean;
    };
    message: string;
    time: string;
};

export type ApiResponseDatabaseSettingsResponse = {
    code: number;
    data?: {
        connectionError?: string | null;
        connectionStatus: string;
        database: string;
        host: string;
        managedByEnvironment: boolean;
        password: string;
        port: number;
        username: string;
    };
    message: string;
    time: string;
};

export type ApiResponseDeleteNavigationGroupResponse = {
    code: number;
    data?: {
        id: string;
        reparentedItems: number;
        title: string;
    };
    message: string;
    time: string;
};

export type ApiResponseDepartmentSyncResponse = {
    code: number;
    data?: {
        created: number;
        disabled: number;
        synchronizedAt: string;
        total: number;
        updated: number;
    };
    message: string;
    time: string;
};

export type ApiResponseDingTalkLoginUserResponse = {
    code: number;
    data?: {
        displayName: string;
        id: string;
        username: string;
    };
    message: string;
    time: string;
};

export type ApiResponseFormBootstrapResponse = {
    code: number;
    data?: {
        metadata: ApiFormSummary;
        navigation: Array<ApiNavigationItem>;
        records: ApiFormRecordList;
        schema: ApiSchemaPayload;
    };
    message: string;
    time: string;
};

export type ApiResponseFormViewResponse = {
    code: number;
    data?: {
        config: unknown;
        name: string;
        updatedAt: string;
        viewUuid: string;
    };
    message: string;
    time: string;
};

export type ApiResponseIdentitySourceSettings = {
    code: number;
    data?: {
        dingtalk: DingTalkSettings;
    };
    message: string;
    time: string;
};

export type ApiResponseInitializeLocalCredentialsResponse = {
    code: number;
    data?: {
        alreadyConfigured: number;
        initialized: number;
        skipped: Array<InitializeLocalCredentialSkip>;
    };
    message: string;
    time: string;
};

export type ApiResponseMarketPurchaseReceipt = {
    code: number;
    data?: {
        licenseId: string;
        orderId: string;
        orderNo: string;
        status: string;
    };
    message: string;
    time: string;
};

export type ApiResponseOrganizationUnitResponse = {
    code: number;
    data?: {
        externalId: string;
        id: string;
        memberCount: number;
        members: Array<OrganizationMemberResponse>;
        name: string;
        parentExternalId?: string | null;
        sourceType: string;
        status: string;
    };
    message: string;
    time: string;
};

export type ApiResponsePlatformLicenseStatus = {
    code: number;
    data?: {
        aiEmployeeStatuses: {
            [key: string]: string;
        };
        aiEmployees: Array<PlatformAiEmployeeEntitlement>;
        deploymentType: string;
        expiresAt?: number | null;
        latestIssuedAt?: number | null;
        latestLicenseId?: string | null;
        licenseCenterUrl?: string | null;
        licenseId?: string | null;
        moduleExpiresAt: {
            [key: string]: number;
        };
        moduleStatuses: {
            [key: string]: string;
        };
        moduleTitles: {
            [key: string]: string;
        };
        modules: Array<string>;
        platformStatus: string;
        reason?: string | null;
        subject?: string | null;
        updateAvailable: boolean;
        valid: boolean;
    };
    message: string;
    time: string;
};

export type ApiResponseProviderResponse = {
    code: number;
    data?: {
        apiBaseUrl: string;
        apiKey: string;
        apiKeyConfigured: boolean;
        defaultChatModel: string;
        enabled: boolean;
        id: string;
        isDefault: boolean;
        kind: string;
        models: Array<string>;
        name: string;
        websiteUrl: string;
    };
    message: string;
    time: string;
};

export type ApiResponseRecycleBinSettings = {
    code: number;
    data?: {
        retentionDays: number;
    };
    message: string;
    time: string;
};

export type ApiResponseRolePermissionsResponse = {
    code: number;
    data?: {
        grants: Array<string>;
        roleId: string;
    };
    message: string;
    time: string;
};

export type ApiResponseRoleResponse = {
    code: number;
    data?: {
        externalId: string;
        id: string;
        memberCount: number;
        name: string;
        sourceType: string;
        status: string;
    };
    message: string;
    time: string;
};

export type ApiResponseSendSmsCodeResponse = {
    code: number;
    data?: {
        expiresIn: number;
    };
    message: string;
    time: string;
};

export type ApiResponseSystemAiStatusResponse = {
    code: number;
    data?: {
        available: boolean;
        providerId?: string | null;
        providerName?: string | null;
        reason?: string | null;
    };
    message: string;
    time: string;
};

export type ApiResponseUserResponse = {
    code: number;
    data?: {
        avatarUrl?: string | null;
        departments: Array<string>;
        displayName: string;
        email?: string | null;
        emailAddresses: Array<EmailAddressResponse>;
        extensionJson: unknown;
        hiredAt?: string | null;
        id: string;
        isAdmin: boolean;
        isBoss: boolean;
        jobNumber?: string | null;
        managerName?: string | null;
        mobile?: string | null;
        primaryDepartment?: string | null;
        realAuthed: boolean;
        remark?: string | null;
        roleIds: Array<string>;
        roles: Array<string>;
        senior: boolean;
        sourceType: string;
        stateCode?: string | null;
        status: string;
        telephone?: string | null;
        tenureMonths?: number | null;
        title?: string | null;
        username?: string | null;
        workPlace?: string | null;
    };
    message: string;
    time: string;
};

export type ApiResponseUserSyncResponse = {
    code: number;
    data?: {
        avatars: number;
        created: number;
        disabled: number;
        memberships: number;
        roleBindings: number;
        roles: number;
        synchronizedAt: string;
        total: number;
        updated: number;
    };
    message: string;
    time: string;
};

export type ApiResponseValkeySettingsResponse = {
    code: number;
    data?: {
        cacheTtlHours: number;
        connectionError?: string | null;
        connectionStatus: string;
        database: number;
        enabled: boolean;
        host: string;
        password: string;
        port: number;
        username: string;
    };
    message: string;
    time: string;
};

export type ApiResponseValue = {
    code: number;
    data?: unknown;
    message: string;
    time: string;
};

export type ApiResponseVecAgentKnowledgeBaseDefinition = {
    code: number;
    data?: Array<{
        content?: string;
        description?: string;
        enabled: boolean;
        id: string;
        name: string;
        retrievalMode: string;
        sourceIds?: Array<string>;
    }>;
    message: string;
    time: string;
};

export type ApiResponseVecAgentPluginDefinition = {
    code: number;
    data?: Array<{
        description?: string;
        enabled: boolean;
        entrypoint?: string;
        id: string;
        manifestJson?: string;
        name: string;
        requiresConfirmation: boolean;
        version: string;
    }>;
    message: string;
    time: string;
};

export type ApiResponseVecAiEmployeeMarketItem = {
    code: number;
    data?: Array<{
        avatarUrl?: string | null;
        billingCycle: string;
        category: string;
        description: string;
        expiresAt?: number | null;
        id: string;
        installed: boolean;
        installedPackageVersion?: string | null;
        installedVersion?: string | null;
        latestPackageVersion: string;
        owned: boolean;
        priceCents: number;
        title: string;
        version: string;
    }>;
    message: string;
    time: string;
};

export type ApiResponseVecApiAgentSession = {
    code: number;
    data?: Array<{
        agentId: string;
        appId?: string | null;
        context: unknown;
        createdAt: string;
        id: string;
        isPinned: boolean;
        modelProvider?: string | null;
        source: string;
        status: string;
        title: string;
        updatedAt: string;
    }>;
    message: string;
    time: string;
};

export type ApiResponseVecApiApp = {
    code: number;
    data?: Array<{
        badge?: string | null;
        color: string;
        createdAt: string;
        deploymentType: string;
        desc: string;
        icon: string;
        id: string;
        name: string;
        onlineReleaseId?: string | null;
        onlineVersion?: string | null;
        owner: string;
        ownerAvatarUrl?: string | null;
        records: number;
    }>;
    message: string;
    time: string;
};

export type ApiResponseVecApiAutomationFlowVersionSummary = {
    code: number;
    data?: Array<{
        changeSummary?: string | null;
        createdAt: string;
        createdBy: string;
        name: string;
        status: AutomationStatus;
        version: number;
    }>;
    message: string;
    time: string;
};

export type ApiResponseVecApiAutomationRun = {
    code: number;
    data?: Array<{
        durationMs?: number | null;
        errorMessage?: string | null;
        finishedAt?: string | null;
        flowVersion: number;
        id: string;
        nodes: Array<ApiAutomationRunNode>;
        retryNodeKey?: string | null;
        retryRunUuid?: string | null;
        retrySource?: string | null;
        startedAt: string;
        status: string;
        triggerEvent: string;
        triggerPayload: unknown;
    }>;
    message: string;
    time: string;
};

export type ApiResponseVecApiDetailForm = {
    code: number;
    data?: Array<{
        detailFormUuid: string;
        primaryDisplayFieldId?: string | null;
        secondaryDisplayFieldId?: string | null;
        sourceFormUuid: string;
        subformFieldId: string;
        title: string;
    }>;
    message: string;
    time: string;
};

export type ApiResponseVecApiFormSummary = {
    code: number;
    data?: Array<{
        category: string;
        count?: number | null;
        createdAt: string;
        formType: FormType;
        id: string;
        latestSchemaVersion: number;
        name: string;
        status: string;
    }>;
    message: string;
    time: string;
};

export type ApiResponseVecApiFormVersionSummary = {
    code: number;
    data?: Array<{
        changeLog?: string | null;
        createdAt: string;
        version: number;
    }>;
    message: string;
    time: string;
};

export type ApiResponseVecApiNavigationItem = {
    code: number;
    data?: Array<{
        id: string;
        isDefaultEntry: boolean;
        itemType: string;
        parentId?: string | null;
        pathSlug: string;
        sortOrder: number;
        targetFormUuid?: string | null;
        title: string;
        visibilityRule?: string | null;
    }>;
    message: string;
    time: string;
};

export type ApiResponseVecCommunicationConversationResponse = {
    code: number;
    data?: Array<{
        conversationType: string;
        id: string;
        lastMessageAt?: string | null;
        lastMessagePreview?: string | null;
        lastMessageSequence: number;
        members: Array<CommunicationMemberResponse>;
        title: string;
        unreadCount: number;
    }>;
    message: string;
    time: string;
};

export type ApiResponseVecCommunicationUserResponse = {
    code: number;
    data?: Array<{
        avatarUrl?: string | null;
        displayName: string;
        id: string;
    }>;
    message: string;
    time: string;
};

export type ApiResponseVecFormViewResponse = {
    code: number;
    data?: Array<{
        config: unknown;
        name: string;
        updatedAt: string;
        viewUuid: string;
    }>;
    message: string;
    time: string;
};

export type ApiResponseVecLocationResponse = {
    code: number;
    data?: Array<{
        code: string;
        depth: number;
        id: string;
        kind: string;
        labels: {
            [key: string]: string;
        };
        name: string;
        parentId?: string | null;
    }>;
    message: string;
    time: string;
};

export type ApiResponseVecOrganizationUnitResponse = {
    code: number;
    data?: Array<{
        externalId: string;
        id: string;
        memberCount: number;
        members: Array<OrganizationMemberResponse>;
        name: string;
        parentExternalId?: string | null;
        sourceType: string;
        status: string;
    }>;
    message: string;
    time: string;
};

export type ApiResponseVecProviderResponse = {
    code: number;
    data?: Array<{
        apiBaseUrl: string;
        apiKey: string;
        apiKeyConfigured: boolean;
        defaultChatModel: string;
        enabled: boolean;
        id: string;
        isDefault: boolean;
        kind: string;
        models: Array<string>;
        name: string;
        websiteUrl: string;
    }>;
    message: string;
    time: string;
};

export type ApiResponseVecRecycleBinEntry = {
    code: number;
    data?: Array<{
        deletedAt: string;
        expiresAt: string;
        formType: string;
        formUuid: string;
        id: string;
        recordData: unknown;
        recordUuid: string;
        sourceAppName?: string | null;
        sourceFormName: string;
    }>;
    message: string;
    time: string;
};

export type ApiResponseVecRoleResponse = {
    code: number;
    data?: Array<{
        externalId: string;
        id: string;
        memberCount: number;
        name: string;
        sourceType: string;
        status: string;
    }>;
    message: string;
    time: string;
};

export type ApiResponseVecUserResponse = {
    code: number;
    data?: Array<{
        avatarUrl?: string | null;
        departments: Array<string>;
        displayName: string;
        email?: string | null;
        emailAddresses: Array<EmailAddressResponse>;
        extensionJson: unknown;
        hiredAt?: string | null;
        id: string;
        isAdmin: boolean;
        isBoss: boolean;
        jobNumber?: string | null;
        managerName?: string | null;
        mobile?: string | null;
        primaryDepartment?: string | null;
        realAuthed: boolean;
        remark?: string | null;
        roleIds: Array<string>;
        roles: Array<string>;
        senior: boolean;
        sourceType: string;
        stateCode?: string | null;
        status: string;
        telephone?: string | null;
        tenureMonths?: number | null;
        title?: string | null;
        username?: string | null;
        workPlace?: string | null;
    }>;
    message: string;
    time: string;
};

export type ApiResponseUsize = {
    code: number;
    data?: number;
    message: string;
    time: string;
};

export type ApiSchemaPayload = {
    formUuid: string;
    latestVersion: number;
    schema: unknown;
    version: number;
};

export type AutomationFlowType = 'trigger' | 'process';

export type AutomationStatus = 'enabled' | 'paused' | 'draft';

export type AutomationTriggerEvent = 'before_create' | 'after_create' | 'before_update' | 'after_update' | 'before_delete' | 'after_delete' | 'form_submit';

export type ClearDingTalkDataResponse = {
    deletedOrganizationUnits: number;
    deletedRolePermissions: number;
    deletedRoles: number;
    deletedUsers: number;
};

export type CommunicationAttachmentResponse = {
    fileId: string;
    isImage: boolean;
    mimeType: string;
    name: string;
    size: number;
};

export type CommunicationAvailabilityResponse = {
    enabled: boolean;
};

export type CommunicationCleanupResponse = {
    deletedFiles: number;
    deletedMessages: number;
};

export type CommunicationConversationResponse = {
    conversationType: string;
    id: string;
    lastMessageAt?: string | null;
    lastMessagePreview?: string | null;
    lastMessageSequence: number;
    members: Array<CommunicationMemberResponse>;
    title: string;
    unreadCount: number;
};

export type CommunicationMemberResponse = {
    avatarUrl?: string | null;
    displayName: string;
    role: string;
    userId: string;
};

export type CommunicationMessagePageResponse = {
    items: Array<CommunicationMessageResponse>;
    nextBeforeSequence?: number | null;
};

export type CommunicationMessageResponse = {
    attachments: Array<CommunicationAttachmentResponse>;
    content: string;
    conversationId: string;
    createdAt: string;
    emailSubject?: string | null;
    fileIds: Array<string>;
    id: string;
    messageType: string;
    replacesMessageId?: string | null;
    senderUserId: string;
    sequence: number;
    status: string;
};

export type CommunicationModuleSettings = {
    allowFileMessages?: boolean;
    allowedFileExtensions?: string;
    expiresAt?: number | null;
    installed?: boolean;
    licenseId?: string | null;
    maxFileUploadMb?: number;
    retentionDays?: number;
    websocketEnabled?: boolean;
};

export type CommunicationStorageStatsResponse = {
    attachmentBytes: number;
    attachmentCount: number;
    conversationCount: number;
    messageBytes: number;
    messageCount: number;
    totalBytes: number;
};

export type CommunicationUserResponse = {
    avatarUrl?: string | null;
    displayName: string;
    id: string;
};

export type CreateAgentSessionRequest = {
    agentId?: string | null;
    context?: null | AgentPageContext;
};

export type CreateAppRequest = {
    description?: string | null;
    icon?: string | null;
    name?: string | null;
};

export type CreateAutomationFlowRequest = {
    description?: string | null;
    name?: string | null;
    operator?: string | null;
    triggerEvent?: null | AutomationTriggerEvent;
    triggerEvents?: Array<AutomationTriggerEvent> | null;
    triggerFormUuid?: string | null;
};

export type CreateDetailFormRequest = {
    primaryDisplayFieldId?: string | null;
    secondaryDisplayFieldId?: string | null;
    subformFieldId: string;
    title?: string | null;
};

export type CreateDirectConversationRequest = {
    userId: string;
};

export type CreateFormRecordRequest = {
    data: unknown;
};

export type CreateFormRequest = {
    formType?: null | FormType;
    parentId?: string | null;
};

export type CreateGroupConversationRequest = {
    memberIds: Array<string>;
    title: string;
};

export type CreateLocalOrganizationUnitRequest = {
    name: string;
    parentExternalId?: string | null;
};

export type CreateLocalRoleRequest = {
    name: string;
};

export type CreateLocalUserRequest = {
    displayName: string;
    email?: string | null;
    mobile?: string | null;
    password: string;
    roleIds: Array<string>;
    title?: string | null;
    username: string;
};

export type CreateNavigationGroupRequest = {
    parent_id?: string | null;
    title: string;
};

export type DatabaseConnectionTestResponse = {
    connected: boolean;
};

export type DatabaseSettingsResponse = {
    connectionError?: string | null;
    connectionStatus: string;
    database: string;
    host: string;
    managedByEnvironment: boolean;
    password: string;
    port: number;
    username: string;
};

export type DeleteNavigationGroupResponse = {
    id: string;
    reparentedItems: number;
    title: string;
};

export type DepartmentSyncResponse = {
    created: number;
    disabled: number;
    synchronizedAt: string;
    total: number;
    updated: number;
};

export type DingTalkLoginRequest = {
    avatarUrl?: string;
    email?: string;
    mobile?: string;
    nick?: string;
    openId?: string;
    unionId?: string;
};

export type DingTalkLoginUserResponse = {
    displayName: string;
    id: string;
    username: string;
};

export type DingTalkSettings = {
    accessToken?: string;
    accessTokenExpiresAt?: string | null;
    agentId: string;
    allowJitProvisioning: boolean;
    appId?: string;
    clientId: string;
    clientSecret: string;
    disableDepartedUsers: boolean;
    includeChildDepartments: boolean;
    syncEnabled: boolean;
    syncIntervalMinutes: number;
};

export type EmailAddressRequest = {
    email: string;
    label: string;
};

export type EmailAddressResponse = {
    email: string;
    label: string;
};

export type FormBootstrapResponse = {
    metadata: ApiFormSummary;
    navigation: Array<ApiNavigationItem>;
    records: ApiFormRecordList;
    schema: ApiSchemaPayload;
};

export type FormType = 'normal' | 'workflow' | 'defined' | 'detail';

export type FormViewResponse = {
    config: unknown;
    name: string;
    updatedAt: string;
    viewUuid: string;
};

export type IdentitySourceSettings = {
    dingtalk: DingTalkSettings;
};

export type ImportLocationsRequest = {
    locations: Array<LocationImportItem>;
};

export type InitializeLocalCredentialSkip = {
    displayName: string;
    reason: string;
    userId: string;
};

export type InitializeLocalCredentialsResponse = {
    alreadyConfigured: number;
    initialized: number;
    skipped: Array<InitializeLocalCredentialSkip>;
};

export type KnowledgeBaseRequest = {
    content?: string;
    description: string;
    enabled: boolean;
    name: string;
    retrievalMode: string;
    sourceIds: Array<string>;
};

export type LocalLoginRequest = {
    password: string;
    username: string;
};

export type LocationImportItem = {
    code: string;
    kind: string;
    labels: {
        [key: string]: string;
    };
    name: string;
    parentCode?: string | null;
    sortOrder?: number | null;
    source?: string | null;
    sourceId?: string | null;
};

export type LocationResponse = {
    code: string;
    depth: number;
    id: string;
    kind: string;
    labels: {
        [key: string]: string;
    };
    name: string;
    parentId?: string | null;
};

export type MarkConversationReadRequest = {
    sequence?: number | null;
};

export type MarketPurchaseReceipt = {
    licenseId: string;
    orderId: string;
    orderNo: string;
    status: string;
};

export type MoveFormNavigationRequest = {
    parent_group_id?: string | null;
};

export type OrganizationMemberResponse = {
    avatarUrl?: string | null;
    displayName: string;
    id: string;
    status: string;
    title?: string | null;
};

export type OrganizationUnitResponse = {
    externalId: string;
    id: string;
    memberCount: number;
    members: Array<OrganizationMemberResponse>;
    name: string;
    parentExternalId?: string | null;
    sourceType: string;
    status: string;
};

export type PlatformAiEmployeeEntitlement = {
    /**
     * Final platform policy assigned to this AI employee by the operation center.
     */
    allowedTools?: Array<string>;
    applicationIds?: Array<string>;
    expiresAt: number;
    id: string;
    skills?: Array<PlatformAiEmployeeSkill>;
    systemPrompt?: string;
    templateVersion?: string;
    title: string;
};

export type PlatformAiEmployeeSkill = {
    description: string;
    id: string;
    instructions: string;
    isSystem?: boolean;
    packageName?: string;
    packagePath?: string;
    /**
     * Canonical DSH Plugin manifest emitted by the operation center/package
     * installer. Kept on the signed entitlement so Host can build its
     * employee-scoped plugin registry without reading the database directly.
     */
    pluginManifestJson?: string;
    requiresConfirmation?: boolean;
    source?: string;
    title: string;
    version?: string;
};

export type PlatformLicenseStatus = {
    aiEmployeeStatuses: {
        [key: string]: string;
    };
    aiEmployees: Array<PlatformAiEmployeeEntitlement>;
    deploymentType: string;
    expiresAt?: number | null;
    latestIssuedAt?: number | null;
    latestLicenseId?: string | null;
    licenseCenterUrl?: string | null;
    licenseId?: string | null;
    moduleExpiresAt: {
        [key: string]: number;
    };
    moduleStatuses: {
        [key: string]: string;
    };
    moduleTitles: {
        [key: string]: string;
    };
    modules: Array<string>;
    platformStatus: string;
    reason?: string | null;
    subject?: string | null;
    updateAvailable: boolean;
    valid: boolean;
};

export type PluginRequest = {
    description: string;
    enabled: boolean;
    entrypoint: string;
    manifestJson?: string;
    name: string;
    requiresConfirmation: boolean;
    version: string;
};

export type ProviderRequest = {
    apiBaseUrl: string;
    apiKey?: string | null;
    defaultChatModel?: string;
    enabled: boolean;
    isDefault?: boolean;
    kind: string;
    models?: Array<string>;
    name: string;
    websiteUrl?: string;
};

export type ProviderResponse = {
    apiBaseUrl: string;
    apiKey: string;
    apiKeyConfigured: boolean;
    defaultChatModel: string;
    enabled: boolean;
    id: string;
    isDefault: boolean;
    kind: string;
    models: Array<string>;
    name: string;
    websiteUrl: string;
};

export type QueryFormRecordsRequest = {
    filters?: Array<RecordFilterRule>;
    page?: number | null;
    pageSize?: number | null;
    sorts?: Array<RecordSortRule>;
};

export type RecallCommunicationMessageRequest = {
    reason?: string | null;
};

export type RecordFilterOperator = 'eq' | 'neq' | 'contains' | 'in' | 'isEmpty' | 'isNotEmpty' | 'gt' | 'gte' | 'lt' | 'lte';

export type RecordFilterRule = {
    fieldId: string;
    operator: RecordFilterOperator;
    value?: unknown;
};

export type RecordSortDirection = 'asc' | 'desc';

export type RecordSortRule = {
    direction: RecordSortDirection;
    fieldId: string;
};

export type RecycleBinEntry = {
    deletedAt: string;
    expiresAt: string;
    formType: string;
    formUuid: string;
    id: string;
    recordData: unknown;
    recordUuid: string;
    sourceAppName?: string | null;
    sourceFormName: string;
};

export type RecycleBinSettings = {
    retentionDays: number;
};

export type ReeditCommunicationMessageRequest = {
    clientMessageId?: string | null;
    content: string;
    emailSubject?: string | null;
    fileIds?: Array<string>;
};

export type ReorderNavigationRequest = {
    item_id: string;
    placement: string;
    target_item_id: string;
};

export type RestoreVersionRequest = {
    change_log?: string | null;
};

export type RolePermissionsResponse = {
    grants: Array<string>;
    roleId: string;
};

export type RoleResponse = {
    externalId: string;
    id: string;
    memberCount: number;
    name: string;
    sourceType: string;
    status: string;
};

export type SaveFormViewRequest = {
    config: unknown;
    name: string;
};

export type SaveSchemaRequest = {
    base_version?: number | null;
    change_log?: string | null;
    schema: unknown;
};

export type SendCommunicationMessageRequest = {
    clientMessageId?: string | null;
    content?: string;
    emailSubject?: string | null;
    fileIds?: Array<string>;
    messageType: string;
};

export type SendSmsCodeRequest = {
    mobile: string;
};

export type SendSmsCodeResponse = {
    expiresIn: number;
};

export type SetDefaultNavigationEntryRequest = {
    form_uuid?: string | null;
    system_page_slug?: string | null;
};

export type SystemAiStatusResponse = {
    available: boolean;
    providerId?: string | null;
    providerName?: string | null;
    reason?: string | null;
};

export type TransferGroupOwnerRequest = {
    userId: string;
};

export type UpdateAgentSessionRequest = {
    isPinned?: boolean | null;
    title?: string | null;
};

export type UpdateAppRequest = {
    description?: string | null;
    icon?: string | null;
    name?: string | null;
};

export type UpdateAutomationFlowRequest = {
    changeSummary?: string | null;
    description?: string | null;
    edges?: unknown;
    name?: string | null;
    nodes?: unknown;
    operator?: string | null;
    status?: null | AutomationStatus;
    triggerConfig?: unknown;
    triggerEvent?: null | AutomationTriggerEvent;
    triggerEvents?: Array<AutomationTriggerEvent> | null;
    triggerFormUuid?: string | null;
};

export type UpdateDatabaseSettingsRequest = {
    database: string;
    host: string;
    password?: string | null;
    port: number;
    username: string;
};

export type UpdateFormNameRequest = {
    name: string;
};

export type UpdateFormRecordRequest = {
    data: unknown;
};

export type UpdateGroupConversationRequest = {
    addMemberIds: Array<string>;
    removeMemberIds: Array<string>;
    title?: string | null;
};

export type UpdateIdentitySourceSettingsRequest = {
    dingtalk: DingTalkSettings;
};

export type UpdateLocalRoleRequest = {
    name?: string | null;
    status?: string | null;
};

export type UpdateNavigationGroupRequest = {
    parent_id?: string | null;
    title: string;
};

export type UpdateRecycleBinSettingsRequest = {
    retentionDays: number;
};

export type UpdateRolePermissionsRequest = {
    grants: Array<string>;
};

export type UpdateUserRequest = {
    displayName?: string | null;
    email?: string | null;
    emailAddresses?: Array<EmailAddressRequest> | null;
    jobNumber?: string | null;
    mobile?: string | null;
    remark?: string | null;
    roleIds?: Array<string> | null;
    status?: string | null;
    telephone?: string | null;
    title?: string | null;
    workPlace?: string | null;
};

export type UpdateValkeySettingsRequest = {
    cacheTtlHours: number;
    database: number;
    enabled: boolean;
    host: string;
    password?: string | null;
    port: number;
    username: string;
};

export type UserResponse = {
    avatarUrl?: string | null;
    departments: Array<string>;
    displayName: string;
    email?: string | null;
    emailAddresses: Array<EmailAddressResponse>;
    extensionJson: unknown;
    hiredAt?: string | null;
    id: string;
    isAdmin: boolean;
    isBoss: boolean;
    jobNumber?: string | null;
    managerName?: string | null;
    mobile?: string | null;
    primaryDepartment?: string | null;
    realAuthed: boolean;
    remark?: string | null;
    roleIds: Array<string>;
    roles: Array<string>;
    senior: boolean;
    sourceType: string;
    stateCode?: string | null;
    status: string;
    telephone?: string | null;
    tenureMonths?: number | null;
    title?: string | null;
    username?: string | null;
    workPlace?: string | null;
};

export type UserSyncResponse = {
    avatars: number;
    created: number;
    disabled: number;
    memberships: number;
    roleBindings: number;
    roles: number;
    synchronizedAt: string;
    total: number;
    updated: number;
};

export type ValkeySettingsResponse = {
    cacheTtlHours: number;
    connectionError?: string | null;
    connectionStatus: string;
    database: number;
    enabled: boolean;
    host: string;
    password: string;
    port: number;
    username: string;
};

export type VerifySmsCodeRequest = {
    code: string;
    mobile: string;
};

export type WorkflowCommentRequest = {
    content: string;
};

export type WorkflowPauseRequest = {
    reason?: string | null;
};

export type WorkflowTaskActionRequest = {
    comment?: string | null;
};

export type ListKnowledgeBasesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/agent/knowledge-bases';
};

export type ListKnowledgeBasesResponses = {
    200: ApiResponseVecAgentKnowledgeBaseDefinition;
};

export type ListKnowledgeBasesResponse = ListKnowledgeBasesResponses[keyof ListKnowledgeBasesResponses];

export type CreateKnowledgeBaseData = {
    body: KnowledgeBaseRequest;
    path?: never;
    query?: never;
    url: '/api/agent/knowledge-bases';
};

export type CreateKnowledgeBaseResponses = {
    200: ApiResponseAgentKnowledgeBaseDefinition;
};

export type CreateKnowledgeBaseResponse = CreateKnowledgeBaseResponses[keyof CreateKnowledgeBaseResponses];

export type DeleteKnowledgeBaseData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/agent/knowledge-bases/{id}';
};

export type DeleteKnowledgeBaseResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type UpdateKnowledgeBaseData = {
    body: KnowledgeBaseRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/agent/knowledge-bases/{id}';
};

export type UpdateKnowledgeBaseResponses = {
    200: ApiResponseAgentKnowledgeBaseDefinition;
};

export type UpdateKnowledgeBaseResponse = UpdateKnowledgeBaseResponses[keyof UpdateKnowledgeBaseResponses];

export type ListPluginsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/agent/plugins';
};

export type ListPluginsResponses = {
    200: ApiResponseVecAgentPluginDefinition;
};

export type ListPluginsResponse = ListPluginsResponses[keyof ListPluginsResponses];

export type CreatePluginData = {
    body: PluginRequest;
    path?: never;
    query?: never;
    url: '/api/agent/plugins';
};

export type CreatePluginResponses = {
    200: ApiResponseAgentPluginDefinition;
};

export type CreatePluginResponse = CreatePluginResponses[keyof CreatePluginResponses];

export type DeletePluginData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/agent/plugins/{id}';
};

export type DeletePluginResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type UpdatePluginData = {
    body: PluginRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/agent/plugins/{id}';
};

export type UpdatePluginResponses = {
    200: ApiResponseAgentPluginDefinition;
};

export type UpdatePluginResponse = UpdatePluginResponses[keyof UpdatePluginResponses];

export type ListProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/agent/providers';
};

export type ListProvidersResponses = {
    200: ApiResponseVecProviderResponse;
};

export type ListProvidersResponse = ListProvidersResponses[keyof ListProvidersResponses];

export type CreateProviderData = {
    body: ProviderRequest;
    path?: never;
    query?: never;
    url: '/api/agent/providers';
};

export type CreateProviderResponses = {
    200: ApiResponseProviderResponse;
};

export type CreateProviderResponse = CreateProviderResponses[keyof CreateProviderResponses];

export type DeleteProviderData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/agent/providers/{id}';
};

export type DeleteProviderResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type UpdateProviderData = {
    body: ProviderRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/agent/providers/{id}';
};

export type UpdateProviderResponses = {
    200: ApiResponseProviderResponse;
};

export type UpdateProviderResponse = UpdateProviderResponses[keyof UpdateProviderResponses];

export type ListAgentSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/agent/sessions';
};

export type ListAgentSessionsResponses = {
    200: ApiResponseVecApiAgentSession;
};

export type ListAgentSessionsResponse = ListAgentSessionsResponses[keyof ListAgentSessionsResponses];

export type CreateAgentSessionData = {
    body: CreateAgentSessionRequest;
    path?: never;
    query?: never;
    url: '/api/agent/sessions';
};

export type CreateAgentSessionResponses = {
    200: ApiResponseApiAgentSession;
};

export type CreateAgentSessionResponse = CreateAgentSessionResponses[keyof CreateAgentSessionResponses];

export type DeleteAgentSessionData = {
    body?: never;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/api/agent/sessions/{sessionId}';
};

export type DeleteAgentSessionResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type UpdateAgentSessionData = {
    body: UpdateAgentSessionRequest;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/api/agent/sessions/{sessionId}';
};

export type UpdateAgentSessionResponses = {
    200: ApiResponseApiAgentSession;
};

export type UpdateAgentSessionResponse = UpdateAgentSessionResponses[keyof UpdateAgentSessionResponses];

export type GetSystemAiStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/agent/system-ai/status';
};

export type GetSystemAiStatusResponses = {
    200: ApiResponseSystemAiStatusResponse;
};

export type GetSystemAiStatusResponse = GetSystemAiStatusResponses[keyof GetSystemAiStatusResponses];

export type ListAppsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/apps';
};

export type ListAppsResponses = {
    200: ApiResponseVecApiApp;
};

export type ListAppsResponse = ListAppsResponses[keyof ListAppsResponses];

export type CreateAppData = {
    body: CreateAppRequest;
    path?: never;
    query?: never;
    url: '/api/apps';
};

export type CreateAppResponses = {
    200: ApiResponseApiApp;
};

export type CreateAppResponse = CreateAppResponses[keyof CreateAppResponses];

export type DeleteAppData = {
    body?: never;
    path: {
        appId: string;
    };
    query?: never;
    url: '/api/apps/{appId}';
};

export type DeleteAppResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type UpdateAppData = {
    body: UpdateAppRequest;
    path: {
        appId: string;
    };
    query?: never;
    url: '/api/apps/{appId}';
};

export type UpdateAppResponses = {
    200: ApiResponseApiApp;
};

export type UpdateAppResponse = UpdateAppResponses[keyof UpdateAppResponses];

export type ListAutomationFlowsData = {
    body?: never;
    path: {
        appId: string;
    };
    query?: never;
    url: '/api/apps/{appId}/automations';
};

export type ListAutomationFlowsResponses = {
    200: ApiResponseApiAutomationFlowList;
};

export type ListAutomationFlowsResponse = ListAutomationFlowsResponses[keyof ListAutomationFlowsResponses];

export type CreateAutomationFlowData = {
    body: CreateAutomationFlowRequest;
    path: {
        appId: string;
    };
    query?: never;
    url: '/api/apps/{appId}/automations';
};

export type CreateAutomationFlowResponses = {
    200: ApiResponseApiAutomationFlow;
};

export type CreateAutomationFlowResponse = CreateAutomationFlowResponses[keyof CreateAutomationFlowResponses];

export type GetAppFieldOutlineData = {
    body?: never;
    path: {
        appId: string;
    };
    query?: never;
    url: '/api/apps/{appId}/field-outline';
};

export type GetAppFieldOutlineResponses = {
    200: ApiResponseApiAppFieldOutline;
};

export type GetAppFieldOutlineResponse = GetAppFieldOutlineResponses[keyof GetAppFieldOutlineResponses];

export type ListFormsData = {
    body?: never;
    path: {
        appId: string;
    };
    query?: never;
    url: '/api/apps/{appId}/forms';
};

export type ListFormsResponses = {
    200: ApiResponseVecApiFormSummary;
};

export type ListFormsResponse = ListFormsResponses[keyof ListFormsResponses];

export type CreateFormData = {
    body: CreateFormRequest;
    path: {
        appId: string;
    };
    query?: never;
    url: '/api/apps/{appId}/forms';
};

export type CreateFormResponses = {
    200: ApiResponseApiFormSummary;
};

export type CreateFormResponse = CreateFormResponses[keyof CreateFormResponses];

export type ListAppNavigationData = {
    body?: never;
    path: {
        appId: string;
    };
    query?: never;
    url: '/api/apps/{appId}/navigation';
};

export type ListAppNavigationResponses = {
    200: ApiResponseVecApiNavigationItem;
};

export type ListAppNavigationResponse = ListAppNavigationResponses[keyof ListAppNavigationResponses];

export type ReorderNavigationItemData = {
    body: ReorderNavigationRequest;
    path: {
        appId: string;
    };
    query?: never;
    url: '/api/apps/{appId}/navigation';
};

export type ReorderNavigationItemResponses = {
    200: ApiResponseVecApiNavigationItem;
};

export type ReorderNavigationItemResponse = ReorderNavigationItemResponses[keyof ReorderNavigationItemResponses];

export type SetDefaultNavigationEntryData = {
    body: SetDefaultNavigationEntryRequest;
    path: {
        appId: string;
    };
    query?: never;
    url: '/api/apps/{appId}/navigation/default-entry';
};

export type SetDefaultNavigationEntryResponses = {
    200: ApiResponseApiNavigationItem;
};

export type SetDefaultNavigationEntryResponse = SetDefaultNavigationEntryResponses[keyof SetDefaultNavigationEntryResponses];

export type MoveFormNavigationData = {
    body: MoveFormNavigationRequest;
    path: {
        appId: string;
        formUuid: string;
    };
    query?: never;
    url: '/api/apps/{appId}/navigation/forms/{formUuid}';
};

export type MoveFormNavigationResponses = {
    200: ApiResponseApiNavigationItem;
};

export type MoveFormNavigationResponse = MoveFormNavigationResponses[keyof MoveFormNavigationResponses];

export type CreateNavigationGroupData = {
    body: CreateNavigationGroupRequest;
    path: {
        appId: string;
    };
    query?: never;
    url: '/api/apps/{appId}/navigation/groups';
};

export type CreateNavigationGroupResponses = {
    200: ApiResponseApiNavigationItem;
};

export type CreateNavigationGroupResponse = CreateNavigationGroupResponses[keyof CreateNavigationGroupResponses];

export type DeleteNavigationGroupData = {
    body?: never;
    path: {
        appId: string;
        groupId: string;
    };
    query?: never;
    url: '/api/apps/{appId}/navigation/groups/{groupId}';
};

export type DeleteNavigationGroupResponses = {
    200: ApiResponseDeleteNavigationGroupResponse;
};

export type DeleteNavigationGroupResponse2 = DeleteNavigationGroupResponses[keyof DeleteNavigationGroupResponses];

export type UpdateNavigationGroupData = {
    body: UpdateNavigationGroupRequest;
    path: {
        appId: string;
        groupId: string;
    };
    query?: never;
    url: '/api/apps/{appId}/navigation/groups/{groupId}';
};

export type UpdateNavigationGroupResponses = {
    200: ApiResponseApiNavigationItem;
};

export type UpdateNavigationGroupResponse = UpdateNavigationGroupResponses[keyof UpdateNavigationGroupResponses];

export type DeleteAutomationFlowData = {
    body?: never;
    path: {
        automationId: string;
    };
    query?: never;
    url: '/api/automations/{automationId}';
};

export type DeleteAutomationFlowResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type GetAutomationFlowData = {
    body?: never;
    path: {
        automationId: string;
    };
    query?: never;
    url: '/api/automations/{automationId}';
};

export type GetAutomationFlowResponses = {
    200: ApiResponseApiAutomationFlowDetail;
};

export type GetAutomationFlowResponse = GetAutomationFlowResponses[keyof GetAutomationFlowResponses];

export type UpdateAutomationFlowData = {
    body: UpdateAutomationFlowRequest;
    path: {
        automationId: string;
    };
    query?: never;
    url: '/api/automations/{automationId}';
};

export type UpdateAutomationFlowResponses = {
    200: ApiResponseApiAutomationFlow;
};

export type UpdateAutomationFlowResponse = UpdateAutomationFlowResponses[keyof UpdateAutomationFlowResponses];

export type ListAutomationFlowRunsData = {
    body?: never;
    path: {
        automationId: string;
    };
    query?: never;
    url: '/api/automations/{automationId}/runs';
};

export type ListAutomationFlowRunsResponses = {
    200: ApiResponseVecApiAutomationRun;
};

export type ListAutomationFlowRunsResponse = ListAutomationFlowRunsResponses[keyof ListAutomationFlowRunsResponses];

export type RetryAutomationFlowRunNodeData = {
    body?: never;
    path: {
        automationId: string;
        runId: string;
        nodeKey: string;
    };
    query?: never;
    url: '/api/automations/{automationId}/runs/{runId}/nodes/{nodeKey}/retry';
};

export type RetryAutomationFlowRunNodeResponses = {
    200: ApiResponseValue;
};

export type RetryAutomationFlowRunNodeResponse = RetryAutomationFlowRunNodeResponses[keyof RetryAutomationFlowRunNodeResponses];

export type RetryAutomationFlowRunData = {
    body?: never;
    path: {
        automationId: string;
        runId: string;
    };
    query?: never;
    url: '/api/automations/{automationId}/runs/{runId}/retry';
};

export type RetryAutomationFlowRunResponses = {
    200: ApiResponseValue;
};

export type RetryAutomationFlowRunResponse = RetryAutomationFlowRunResponses[keyof RetryAutomationFlowRunResponses];

export type ListAutomationFlowVersionsData = {
    body?: never;
    path: {
        automationId: string;
    };
    query?: never;
    url: '/api/automations/{automationId}/versions';
};

export type ListAutomationFlowVersionsResponses = {
    200: ApiResponseVecApiAutomationFlowVersionSummary;
};

export type ListAutomationFlowVersionsResponse = ListAutomationFlowVersionsResponses[keyof ListAutomationFlowVersionsResponses];

export type RestoreAutomationFlowVersionData = {
    body: RestoreVersionRequest;
    path: {
        automationId: string;
        version: number;
    };
    query?: never;
    url: '/api/automations/{automationId}/versions/{version}/restore';
};

export type RestoreAutomationFlowVersionResponses = {
    200: ApiResponseApiAutomationFlowDetail;
};

export type RestoreAutomationFlowVersionResponse = RestoreAutomationFlowVersionResponses[keyof RestoreAutomationFlowVersionResponses];

export type ListCommunicationConversationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/communication/conversations';
};

export type ListCommunicationConversationsResponses = {
    200: ApiResponseVecCommunicationConversationResponse;
};

export type ListCommunicationConversationsResponse = ListCommunicationConversationsResponses[keyof ListCommunicationConversationsResponses];

export type CreateDirectConversationData = {
    body: CreateDirectConversationRequest;
    path?: never;
    query?: never;
    url: '/api/communication/conversations/direct';
};

export type CreateDirectConversationResponses = {
    200: ApiResponseCommunicationConversationResponse;
};

export type CreateDirectConversationResponse = CreateDirectConversationResponses[keyof CreateDirectConversationResponses];

export type CreateGroupConversationData = {
    body: CreateGroupConversationRequest;
    path?: never;
    query?: never;
    url: '/api/communication/conversations/groups';
};

export type CreateGroupConversationResponses = {
    200: ApiResponseCommunicationConversationResponse;
};

export type CreateGroupConversationResponse = CreateGroupConversationResponses[keyof CreateGroupConversationResponses];

export type UpdateGroupConversationData = {
    body: UpdateGroupConversationRequest;
    path: {
        conversationId: string;
    };
    query?: never;
    url: '/api/communication/conversations/{conversationId}';
};

export type UpdateGroupConversationResponses = {
    200: ApiResponseCommunicationConversationResponse;
};

export type UpdateGroupConversationResponse = UpdateGroupConversationResponses[keyof UpdateGroupConversationResponses];

export type DeleteGroupConversationData = {
    body: unknown;
    path: {
        conversationId: string;
    };
    query?: never;
    url: '/api/communication/conversations/{conversationId}/dissolve';
};

export type DeleteGroupConversationResponses = {
    200: ApiResponseValue;
};

export type DeleteGroupConversationResponse = DeleteGroupConversationResponses[keyof DeleteGroupConversationResponses];

export type LeaveGroupConversationData = {
    body: unknown;
    path: {
        conversationId: string;
    };
    query?: never;
    url: '/api/communication/conversations/{conversationId}/leave';
};

export type LeaveGroupConversationResponses = {
    200: ApiResponseValue;
};

export type LeaveGroupConversationResponse = LeaveGroupConversationResponses[keyof LeaveGroupConversationResponses];

export type ListCommunicationMessagesData = {
    body?: never;
    path: {
        conversationId: string;
    };
    query?: {
        beforeSequence?: number;
        limit?: number;
    };
    url: '/api/communication/conversations/{conversationId}/messages';
};

export type ListCommunicationMessagesResponses = {
    200: ApiResponseCommunicationMessagePageResponse;
};

export type ListCommunicationMessagesResponse = ListCommunicationMessagesResponses[keyof ListCommunicationMessagesResponses];

export type SendCommunicationMessageData = {
    body: SendCommunicationMessageRequest;
    path: {
        conversationId: string;
    };
    query?: never;
    url: '/api/communication/conversations/{conversationId}/messages';
};

export type SendCommunicationMessageResponses = {
    200: ApiResponseCommunicationMessageResponse;
};

export type SendCommunicationMessageResponse = SendCommunicationMessageResponses[keyof SendCommunicationMessageResponses];

export type RecallCommunicationMessageData = {
    body: RecallCommunicationMessageRequest;
    path: {
        conversationId: string;
        messageId: string;
    };
    query?: never;
    url: '/api/communication/conversations/{conversationId}/messages/{messageId}/recall';
};

export type RecallCommunicationMessageResponses = {
    200: ApiResponseCommunicationMessageResponse;
};

export type RecallCommunicationMessageResponse = RecallCommunicationMessageResponses[keyof RecallCommunicationMessageResponses];

export type ReeditCommunicationMessageData = {
    body: ReeditCommunicationMessageRequest;
    path: {
        conversationId: string;
        messageId: string;
    };
    query?: never;
    url: '/api/communication/conversations/{conversationId}/messages/{messageId}/reedit';
};

export type ReeditCommunicationMessageResponses = {
    200: ApiResponseCommunicationMessageResponse;
};

export type ReeditCommunicationMessageResponse = ReeditCommunicationMessageResponses[keyof ReeditCommunicationMessageResponses];

export type TransferGroupOwnerData = {
    body: TransferGroupOwnerRequest;
    path: {
        conversationId: string;
    };
    query?: never;
    url: '/api/communication/conversations/{conversationId}/owner';
};

export type TransferGroupOwnerResponses = {
    200: ApiResponseCommunicationConversationResponse;
};

export type TransferGroupOwnerResponse = TransferGroupOwnerResponses[keyof TransferGroupOwnerResponses];

export type MarkCommunicationConversationReadData = {
    body: MarkConversationReadRequest;
    path: {
        conversationId: string;
    };
    query?: never;
    url: '/api/communication/conversations/{conversationId}/read';
};

export type MarkCommunicationConversationReadResponses = {
    200: ApiResponseValue;
};

export type MarkCommunicationConversationReadResponse = MarkCommunicationConversationReadResponses[keyof MarkCommunicationConversationReadResponses];

export type GetCommunicationStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/communication/status';
};

export type GetCommunicationStatusResponses = {
    200: ApiResponseCommunicationAvailabilityResponse;
};

export type GetCommunicationStatusResponse = GetCommunicationStatusResponses[keyof GetCommunicationStatusResponses];

export type ListCommunicationUsersData = {
    body?: never;
    path?: never;
    query?: {
        query?: string;
    };
    url: '/api/communication/users';
};

export type ListCommunicationUsersResponses = {
    200: ApiResponseVecCommunicationUserResponse;
};

export type ListCommunicationUsersResponse = ListCommunicationUsersResponses[keyof ListCommunicationUsersResponses];

export type GetFormSchemaContractData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/form-schema-contract';
};

export type GetFormSchemaContractResponses = {
    200: ApiResponseValue;
};

export type GetFormSchemaContractResponse = GetFormSchemaContractResponses[keyof GetFormSchemaContractResponses];

export type DeleteFormData = {
    body?: never;
    path: {
        formUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}';
};

export type DeleteFormResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type GetFormData = {
    body?: never;
    path: {
        formUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}';
};

export type GetFormResponses = {
    200: ApiResponseApiFormSummary;
};

export type GetFormResponse = GetFormResponses[keyof GetFormResponses];

export type UpdateFormNameData = {
    body: UpdateFormNameRequest;
    path: {
        formUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}';
};

export type UpdateFormNameResponses = {
    200: ApiResponseApiSchemaPayload;
};

export type UpdateFormNameResponse = UpdateFormNameResponses[keyof UpdateFormNameResponses];

export type GetFormBootstrapData = {
    body?: never;
    path: {
        formUuid: string;
    };
    query: {
        appId: string;
        page?: number;
        pageSize?: number;
    };
    url: '/api/forms/{formUuid}/bootstrap';
};

export type GetFormBootstrapResponses = {
    200: ApiResponseFormBootstrapResponse;
};

export type GetFormBootstrapResponse = GetFormBootstrapResponses[keyof GetFormBootstrapResponses];

export type ListDetailFormsData = {
    body?: never;
    path: {
        formUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/detail-forms';
};

export type ListDetailFormsResponses = {
    200: ApiResponseVecApiDetailForm;
};

export type ListDetailFormsResponse = ListDetailFormsResponses[keyof ListDetailFormsResponses];

export type CreateDetailFormData = {
    body: CreateDetailFormRequest;
    path: {
        formUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/detail-forms';
};

export type CreateDetailFormResponses = {
    200: ApiResponseApiDetailForm;
};

export type CreateDetailFormResponse = CreateDetailFormResponses[keyof CreateDetailFormResponses];

export type ListFormRecordsData = {
    body?: never;
    path: {
        formUuid: string;
    };
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/forms/{formUuid}/records';
};

export type ListFormRecordsResponses = {
    200: ApiResponseApiFormRecordList;
};

export type ListFormRecordsResponse = ListFormRecordsResponses[keyof ListFormRecordsResponses];

export type CreateFormRecordData = {
    body: CreateFormRecordRequest;
    path: {
        formUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/records';
};

export type CreateFormRecordResponses = {
    200: ApiResponseApiFormRecord;
};

export type CreateFormRecordResponse = CreateFormRecordResponses[keyof CreateFormRecordResponses];

export type QueryFormRecordsData = {
    body: QueryFormRecordsRequest;
    path: {
        formUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/records/query';
};

export type QueryFormRecordsResponses = {
    200: ApiResponseApiFormRecordList;
};

export type QueryFormRecordsResponse = QueryFormRecordsResponses[keyof QueryFormRecordsResponses];

export type DeleteFormRecordData = {
    body?: never;
    path: {
        formUuid: string;
        recordUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/records/{recordUuid}';
};

export type DeleteFormRecordResponses = {
    200: ApiResponseValue;
};

export type DeleteFormRecordResponse = DeleteFormRecordResponses[keyof DeleteFormRecordResponses];

export type UpdateFormRecordData = {
    body: UpdateFormRecordRequest;
    path: {
        formUuid: string;
        recordUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/records/{recordUuid}';
};

export type UpdateFormRecordResponses = {
    200: ApiResponseApiFormRecord;
};

export type UpdateFormRecordResponse = UpdateFormRecordResponses[keyof UpdateFormRecordResponses];

export type GetWorkflowRecordRuntimeData = {
    body?: never;
    path: {
        formUuid: string;
        recordUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/records/{recordUuid}/workflow';
};

export type GetWorkflowRecordRuntimeResponses = {
    200: ApiResponseValue;
};

export type GetWorkflowRecordRuntimeResponse = GetWorkflowRecordRuntimeResponses[keyof GetWorkflowRecordRuntimeResponses];

export type ListWorkflowCommentsData = {
    body?: never;
    path: {
        formUuid: string;
        recordUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/records/{recordUuid}/workflow/comments';
};

export type ListWorkflowCommentsResponses = {
    200: ApiResponseValue;
};

export type ListWorkflowCommentsResponse = ListWorkflowCommentsResponses[keyof ListWorkflowCommentsResponses];

export type CreateWorkflowCommentData = {
    body: WorkflowCommentRequest;
    path: {
        formUuid: string;
        recordUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/records/{recordUuid}/workflow/comments';
};

export type CreateWorkflowCommentResponses = {
    200: ApiResponseValue;
};

export type CreateWorkflowCommentResponse = CreateWorkflowCommentResponses[keyof CreateWorkflowCommentResponses];

export type PauseWorkflowRecordData = {
    body: WorkflowPauseRequest;
    path: {
        formUuid: string;
        recordUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/records/{recordUuid}/workflow/pause';
};

export type PauseWorkflowRecordResponses = {
    200: ApiResponseValue;
};

export type PauseWorkflowRecordResponse = PauseWorkflowRecordResponses[keyof PauseWorkflowRecordResponses];

export type ResumeWorkflowRecordData = {
    body?: never;
    path: {
        formUuid: string;
        recordUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/records/{recordUuid}/workflow/resume';
};

export type ResumeWorkflowRecordResponses = {
    200: ApiResponseValue;
};

export type ResumeWorkflowRecordResponse = ResumeWorkflowRecordResponses[keyof ResumeWorkflowRecordResponses];

export type ReverseWorkflowRecordData = {
    body?: never;
    path: {
        formUuid: string;
        recordUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/records/{recordUuid}/workflow/reverse';
};

export type ReverseWorkflowRecordResponses = {
    200: ApiResponseValue;
};

export type ReverseWorkflowRecordResponse = ReverseWorkflowRecordResponses[keyof ReverseWorkflowRecordResponses];

export type SubmitWorkflowRecordData = {
    body?: never;
    path: {
        formUuid: string;
        recordUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/records/{recordUuid}/workflow/submit';
};

export type SubmitWorkflowRecordResponses = {
    200: ApiResponseValue;
};

export type SubmitWorkflowRecordResponse = SubmitWorkflowRecordResponses[keyof SubmitWorkflowRecordResponses];

export type GetFormSchemaData = {
    body?: never;
    path: {
        formUuid: string;
    };
    query?: {
        version?: number;
    };
    url: '/api/forms/{formUuid}/schema';
};

export type GetFormSchemaResponses = {
    200: ApiResponseApiSchemaPayload;
};

export type GetFormSchemaResponse = GetFormSchemaResponses[keyof GetFormSchemaResponses];

export type SaveFormSchemaData = {
    body: SaveSchemaRequest;
    path: {
        formUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/schema';
};

export type SaveFormSchemaResponses = {
    200: ApiResponseApiSchemaPayload;
};

export type SaveFormSchemaResponse = SaveFormSchemaResponses[keyof SaveFormSchemaResponses];

export type ListFormVersionsData = {
    body?: never;
    path: {
        formUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/versions';
};

export type ListFormVersionsResponses = {
    200: ApiResponseVecApiFormVersionSummary;
};

export type ListFormVersionsResponse = ListFormVersionsResponses[keyof ListFormVersionsResponses];

export type GetFormVersionData = {
    body?: never;
    path: {
        formUuid: string;
        version: number;
    };
    query?: never;
    url: '/api/forms/{formUuid}/versions/{version}';
};

export type GetFormVersionResponses = {
    200: ApiResponseApiSchemaPayload;
};

export type GetFormVersionResponse = GetFormVersionResponses[keyof GetFormVersionResponses];

export type RestoreFormVersionData = {
    body: RestoreVersionRequest;
    path: {
        formUuid: string;
        version: number;
    };
    query?: never;
    url: '/api/forms/{formUuid}/versions/{version}/restore';
};

export type RestoreFormVersionResponses = {
    200: ApiResponseApiSchemaPayload;
};

export type RestoreFormVersionResponse = RestoreFormVersionResponses[keyof RestoreFormVersionResponses];

export type ListFormViewsData = {
    body?: never;
    path: {
        formUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/views';
};

export type ListFormViewsResponses = {
    200: ApiResponseVecFormViewResponse;
};

export type ListFormViewsResponse = ListFormViewsResponses[keyof ListFormViewsResponses];

export type CreateFormViewData = {
    body: SaveFormViewRequest;
    path: {
        formUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/views';
};

export type CreateFormViewResponses = {
    200: ApiResponseFormViewResponse;
};

export type CreateFormViewResponse = CreateFormViewResponses[keyof CreateFormViewResponses];

export type DeleteFormViewData = {
    body?: never;
    path: {
        formUuid: string;
        viewUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/views/{viewUuid}';
};

export type DeleteFormViewResponses = {
    /**
     * Form view deleted
     */
    200: unknown;
};

export type UpdateFormViewData = {
    body: SaveFormViewRequest;
    path: {
        formUuid: string;
        viewUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/views/{viewUuid}';
};

export type UpdateFormViewResponses = {
    200: ApiResponseFormViewResponse;
};

export type UpdateFormViewResponse = UpdateFormViewResponses[keyof UpdateFormViewResponses];

export type EnsureWorkflowProcessFlowData = {
    body?: never;
    path: {
        formUuid: string;
    };
    query?: never;
    url: '/api/forms/{formUuid}/workflow/process';
};

export type EnsureWorkflowProcessFlowResponses = {
    200: ApiResponseApiAutomationFlow;
};

export type EnsureWorkflowProcessFlowResponse = EnsureWorkflowProcessFlowResponses[keyof EnsureWorkflowProcessFlowResponses];

export type ResolveDingTalkLoginData = {
    body: DingTalkLoginRequest;
    path?: never;
    query?: never;
    url: '/api/identity/dingtalk/session';
};

export type ResolveDingTalkLoginResponses = {
    200: ApiResponseDingTalkLoginUserResponse;
};

export type ResolveDingTalkLoginResponse = ResolveDingTalkLoginResponses[keyof ResolveDingTalkLoginResponses];

export type LocalLoginData = {
    body: LocalLoginRequest;
    path?: never;
    query?: never;
    url: '/api/identity/local-login';
};

export type LocalLoginResponses = {
    200: ApiResponseDingTalkLoginUserResponse;
};

export type LocalLoginResponse = LocalLoginResponses[keyof LocalLoginResponses];

export type ListOrganizationUnitsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/identity/organization-units';
};

export type ListOrganizationUnitsResponses = {
    200: ApiResponseVecOrganizationUnitResponse;
};

export type ListOrganizationUnitsResponse = ListOrganizationUnitsResponses[keyof ListOrganizationUnitsResponses];

export type CreateLocalOrganizationUnitData = {
    body: CreateLocalOrganizationUnitRequest;
    path?: never;
    query?: never;
    url: '/api/identity/organization-units';
};

export type CreateLocalOrganizationUnitResponses = {
    200: ApiResponseOrganizationUnitResponse;
};

export type CreateLocalOrganizationUnitResponse = CreateLocalOrganizationUnitResponses[keyof CreateLocalOrganizationUnitResponses];

export type ListRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/identity/roles';
};

export type ListRolesResponses = {
    200: ApiResponseVecRoleResponse;
};

export type ListRolesResponse = ListRolesResponses[keyof ListRolesResponses];

export type CreateLocalRoleData = {
    body: CreateLocalRoleRequest;
    path?: never;
    query?: never;
    url: '/api/identity/roles';
};

export type CreateLocalRoleResponses = {
    200: ApiResponseRoleResponse;
};

export type CreateLocalRoleResponse = CreateLocalRoleResponses[keyof CreateLocalRoleResponses];

export type DeleteLocalRoleData = {
    body?: never;
    path: {
        roleId: string;
    };
    query?: never;
    url: '/api/identity/roles/{roleId}';
};

export type DeleteLocalRoleResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type UpdateLocalRoleData = {
    body: UpdateLocalRoleRequest;
    path: {
        roleId: string;
    };
    query?: never;
    url: '/api/identity/roles/{roleId}';
};

export type UpdateLocalRoleResponses = {
    200: ApiResponseRoleResponse;
};

export type UpdateLocalRoleResponse = UpdateLocalRoleResponses[keyof UpdateLocalRoleResponses];

export type VerifySmsCodeData = {
    body: VerifySmsCodeRequest;
    path?: never;
    query?: never;
    url: '/api/identity/sms/login';
};

export type VerifySmsCodeResponses = {
    200: ApiResponseDingTalkLoginUserResponse;
};

export type VerifySmsCodeResponse = VerifySmsCodeResponses[keyof VerifySmsCodeResponses];

export type SendSmsCodeData = {
    body: SendSmsCodeRequest;
    path?: never;
    query?: never;
    url: '/api/identity/sms/send-code';
};

export type SendSmsCodeResponses = {
    200: ApiResponseSendSmsCodeResponse;
};

export type SendSmsCodeResponse2 = SendSmsCodeResponses[keyof SendSmsCodeResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/identity/users';
};

export type ListUsersResponses = {
    200: ApiResponseVecUserResponse;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateLocalUserData = {
    body: CreateLocalUserRequest;
    path?: never;
    query?: never;
    url: '/api/identity/users';
};

export type CreateLocalUserResponses = {
    200: ApiResponseDingTalkLoginUserResponse;
};

export type CreateLocalUserResponse = CreateLocalUserResponses[keyof CreateLocalUserResponses];

export type InitializeLocalCredentialsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/identity/users/initialize-local-credentials';
};

export type InitializeLocalCredentialsResponses = {
    200: ApiResponseInitializeLocalCredentialsResponse;
};

export type InitializeLocalCredentialsResponse2 = InitializeLocalCredentialsResponses[keyof InitializeLocalCredentialsResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/identity/users/{userId}';
};

export type DeleteUserResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type UpdateUserData = {
    body: UpdateUserRequest;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/identity/users/{userId}';
};

export type UpdateUserResponses = {
    200: ApiResponseUserResponse;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type GetInternalIdentitySourceSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/internal/identity-source';
};

export type GetInternalIdentitySourceSettingsResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ListLocationsData = {
    body?: never;
    path?: never;
    query?: {
        parentCode?: string;
        depth?: number;
        query?: string;
        limit?: number;
    };
    url: '/api/locations';
};

export type ListLocationsResponses = {
    200: ApiResponseVecLocationResponse;
};

export type ListLocationsResponse = ListLocationsResponses[keyof ListLocationsResponses];

export type ImportLocationsData = {
    body: ImportLocationsRequest;
    path?: never;
    query?: never;
    url: '/api/locations';
};

export type ImportLocationsResponses = {
    200: ApiResponseUsize;
};

export type ImportLocationsResponse = ImportLocationsResponses[keyof ImportLocationsResponses];

export type EmptyRecycleBinData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/recycle-bin';
};

export type EmptyRecycleBinResponses = {
    200: ApiResponseValue;
};

export type EmptyRecycleBinResponse = EmptyRecycleBinResponses[keyof EmptyRecycleBinResponses];

export type ListRecycleBinData = {
    body?: never;
    path?: never;
    query?: {
        formUuid?: string;
    };
    url: '/api/recycle-bin';
};

export type ListRecycleBinResponses = {
    200: ApiResponseVecRecycleBinEntry;
};

export type ListRecycleBinResponse = ListRecycleBinResponses[keyof ListRecycleBinResponses];

export type DeleteRecycleBinEntryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/recycle-bin/{id}';
};

export type DeleteRecycleBinEntryResponses = {
    200: ApiResponseValue;
};

export type DeleteRecycleBinEntryResponse = DeleteRecycleBinEntryResponses[keyof DeleteRecycleBinEntryResponses];

export type RestoreRecycleBinEntryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/recycle-bin/{id}/restore';
};

export type RestoreRecycleBinEntryResponses = {
    200: ApiResponseValue;
};

export type RestoreRecycleBinEntryResponse = RestoreRecycleBinEntryResponses[keyof RestoreRecycleBinEntryResponses];

export type GetAiEmployeeMarketData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/ai-employee-market';
};

export type GetAiEmployeeMarketResponses = {
    200: ApiResponseVecAiEmployeeMarketItem;
};

export type GetAiEmployeeMarketResponse = GetAiEmployeeMarketResponses[keyof GetAiEmployeeMarketResponses];

export type InstallAiEmployeeData = {
    body?: never;
    path: {
        employee_id: string;
    };
    query?: never;
    url: '/api/settings/ai-employee-market/{employee_id}/install';
};

export type InstallAiEmployeeResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type TestPurchaseAiEmployeeData = {
    body?: never;
    path: {
        employee_id: string;
    };
    query?: never;
    url: '/api/settings/ai-employee-market/{employee_id}/test-purchase';
};

export type TestPurchaseAiEmployeeResponses = {
    200: ApiResponseMarketPurchaseReceipt;
};

export type TestPurchaseAiEmployeeResponse = TestPurchaseAiEmployeeResponses[keyof TestPurchaseAiEmployeeResponses];

export type GetCommunicationModuleSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/communication';
};

export type GetCommunicationModuleSettingsResponses = {
    200: ApiResponseCommunicationModuleSettings;
};

export type GetCommunicationModuleSettingsResponse = GetCommunicationModuleSettingsResponses[keyof GetCommunicationModuleSettingsResponses];

export type UpdateCommunicationModuleSettingsData = {
    body: CommunicationModuleSettings;
    path?: never;
    query?: never;
    url: '/api/settings/communication';
};

export type UpdateCommunicationModuleSettingsResponses = {
    200: ApiResponseCommunicationModuleSettings;
};

export type UpdateCommunicationModuleSettingsResponse = UpdateCommunicationModuleSettingsResponses[keyof UpdateCommunicationModuleSettingsResponses];

export type CleanupCommunicationDataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/communication/cleanup';
};

export type CleanupCommunicationDataResponses = {
    200: ApiResponseCommunicationCleanupResponse;
};

export type CleanupCommunicationDataResponse = CleanupCommunicationDataResponses[keyof CleanupCommunicationDataResponses];

export type GetCommunicationStorageStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/communication/storage';
};

export type GetCommunicationStorageStatsResponses = {
    200: ApiResponseCommunicationStorageStatsResponse;
};

export type GetCommunicationStorageStatsResponse = GetCommunicationStorageStatsResponses[keyof GetCommunicationStorageStatsResponses];

export type GetDatabaseSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/database';
};

export type GetDatabaseSettingsResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type UpdateDatabaseSettingsData = {
    body: UpdateDatabaseSettingsRequest;
    path?: never;
    query?: never;
    url: '/api/settings/database';
};

export type UpdateDatabaseSettingsResponses = {
    200: ApiResponseDatabaseSettingsResponse;
};

export type UpdateDatabaseSettingsResponse = UpdateDatabaseSettingsResponses[keyof UpdateDatabaseSettingsResponses];

export type TestDatabaseConnectionData = {
    body: UpdateDatabaseSettingsRequest;
    path?: never;
    query?: never;
    url: '/api/settings/database/test';
};

export type TestDatabaseConnectionResponses = {
    200: ApiResponseDatabaseConnectionTestResponse;
};

export type TestDatabaseConnectionResponse = TestDatabaseConnectionResponses[keyof TestDatabaseConnectionResponses];

export type GetIdentitySourceSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/identity-source';
};

export type GetIdentitySourceSettingsResponses = {
    200: ApiResponseIdentitySourceSettings;
};

export type GetIdentitySourceSettingsResponse = GetIdentitySourceSettingsResponses[keyof GetIdentitySourceSettingsResponses];

export type UpdateIdentitySourceSettingsData = {
    body: UpdateIdentitySourceSettingsRequest;
    path?: never;
    query?: never;
    url: '/api/settings/identity-source';
};

export type UpdateIdentitySourceSettingsResponses = {
    200: ApiResponseIdentitySourceSettings;
};

export type UpdateIdentitySourceSettingsResponse = UpdateIdentitySourceSettingsResponses[keyof UpdateIdentitySourceSettingsResponses];

export type RefreshDingTalkAccessTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/identity-source/dingtalk/access-token';
};

export type RefreshDingTalkAccessTokenResponses = {
    200: ApiResponseAccessTokenResponse;
};

export type RefreshDingTalkAccessTokenResponse = RefreshDingTalkAccessTokenResponses[keyof RefreshDingTalkAccessTokenResponses];

export type ClearDingTalkDataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/identity-source/dingtalk/clear';
};

export type ClearDingTalkDataResponses = {
    200: ApiResponseClearDingTalkDataResponse;
};

export type ClearDingTalkDataResponse2 = ClearDingTalkDataResponses[keyof ClearDingTalkDataResponses];

export type SyncDingTalkDepartmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/identity-source/dingtalk/sync-departments';
};

export type SyncDingTalkDepartmentsResponses = {
    200: ApiResponseDepartmentSyncResponse;
};

export type SyncDingTalkDepartmentsResponse = SyncDingTalkDepartmentsResponses[keyof SyncDingTalkDepartmentsResponses];

export type SyncDingTalkUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/identity-source/dingtalk/sync-users';
};

export type SyncDingTalkUsersResponses = {
    200: ApiResponseUserSyncResponse;
};

export type SyncDingTalkUsersResponse = SyncDingTalkUsersResponses[keyof SyncDingTalkUsersResponses];

export type GetPlatformLicenseStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/license';
};

export type GetPlatformLicenseStatusResponses = {
    200: ApiResponsePlatformLicenseStatus;
};

export type GetPlatformLicenseStatusResponse = GetPlatformLicenseStatusResponses[keyof GetPlatformLicenseStatusResponses];

export type ActivatePlatformLicenseData = {
    body: ActivatePlatformLicenseRequest;
    path?: never;
    query?: never;
    url: '/api/settings/license';
};

export type ActivatePlatformLicenseResponses = {
    200: ApiResponsePlatformLicenseStatus;
};

export type ActivatePlatformLicenseResponse = ActivatePlatformLicenseResponses[keyof ActivatePlatformLicenseResponses];

export type ApplyLatestPlatformLicenseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/license/latest';
};

export type ApplyLatestPlatformLicenseResponses = {
    200: ApiResponsePlatformLicenseStatus;
};

export type ApplyLatestPlatformLicenseResponse = ApplyLatestPlatformLicenseResponses[keyof ApplyLatestPlatformLicenseResponses];

export type GetRolePermissionsData = {
    body?: never;
    path: {
        roleId: string;
    };
    query?: never;
    url: '/api/settings/permissions/{roleId}';
};

export type GetRolePermissionsResponses = {
    200: ApiResponseRolePermissionsResponse;
};

export type GetRolePermissionsResponse = GetRolePermissionsResponses[keyof GetRolePermissionsResponses];

export type UpdateRolePermissionsData = {
    body: UpdateRolePermissionsRequest;
    path: {
        roleId: string;
    };
    query?: never;
    url: '/api/settings/permissions/{roleId}';
};

export type UpdateRolePermissionsResponses = {
    200: ApiResponseRolePermissionsResponse;
};

export type UpdateRolePermissionsResponse = UpdateRolePermissionsResponses[keyof UpdateRolePermissionsResponses];

export type GetRecycleBinSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/recycle-bin';
};

export type GetRecycleBinSettingsResponses = {
    200: ApiResponseRecycleBinSettings;
};

export type GetRecycleBinSettingsResponse = GetRecycleBinSettingsResponses[keyof GetRecycleBinSettingsResponses];

export type UpdateRecycleBinSettingsData = {
    body: UpdateRecycleBinSettingsRequest;
    path?: never;
    query?: never;
    url: '/api/settings/recycle-bin';
};

export type UpdateRecycleBinSettingsResponses = {
    200: ApiResponseRecycleBinSettings;
};

export type UpdateRecycleBinSettingsResponse = UpdateRecycleBinSettingsResponses[keyof UpdateRecycleBinSettingsResponses];

export type GetValkeySettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/valkey';
};

export type GetValkeySettingsResponses = {
    200: ApiResponseValkeySettingsResponse;
};

export type GetValkeySettingsResponse = GetValkeySettingsResponses[keyof GetValkeySettingsResponses];

export type UpdateValkeySettingsData = {
    body: UpdateValkeySettingsRequest;
    path?: never;
    query?: never;
    url: '/api/settings/valkey';
};

export type UpdateValkeySettingsResponses = {
    200: ApiResponseValkeySettingsResponse;
};

export type UpdateValkeySettingsResponse = UpdateValkeySettingsResponses[keyof UpdateValkeySettingsResponses];

export type TestValkeyConnectionData = {
    body: UpdateValkeySettingsRequest;
    path?: never;
    query?: never;
    url: '/api/settings/valkey/test';
};

export type TestValkeyConnectionResponses = {
    200: ApiResponseDatabaseConnectionTestResponse;
};

export type TestValkeyConnectionResponse = TestValkeyConnectionResponses[keyof TestValkeyConnectionResponses];

export type ListWorkflowNotificationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/workflow/notifications';
};

export type ListWorkflowNotificationsResponses = {
    200: ApiResponseValue;
};

export type ListWorkflowNotificationsResponse = ListWorkflowNotificationsResponses[keyof ListWorkflowNotificationsResponses];

export type ReadWorkflowNotificationData = {
    body?: never;
    path: {
        notificationUuid: string;
    };
    query?: never;
    url: '/api/workflow/notifications/{notificationUuid}/read';
};

export type ReadWorkflowNotificationResponses = {
    200: ApiResponseValue;
};

export type ReadWorkflowNotificationResponse = ReadWorkflowNotificationResponses[keyof ReadWorkflowNotificationResponses];

export type ListWorkflowTasksData = {
    body?: never;
    path?: never;
    query: {
        appId?: string;
        scope: string;
    };
    url: '/api/workflow/tasks';
};

export type ListWorkflowTasksResponses = {
    200: ApiResponseValue;
};

export type ListWorkflowTasksResponse = ListWorkflowTasksResponses[keyof ListWorkflowTasksResponses];

export type ApproveWorkflowTaskData = {
    body: WorkflowTaskActionRequest;
    path: {
        taskUuid: string;
    };
    query?: never;
    url: '/api/workflow/tasks/{taskUuid}/approve';
};

export type ApproveWorkflowTaskResponses = {
    200: ApiResponseValue;
};

export type ApproveWorkflowTaskResponse = ApproveWorkflowTaskResponses[keyof ApproveWorkflowTaskResponses];

export type RejectWorkflowTaskData = {
    body: WorkflowTaskActionRequest;
    path: {
        taskUuid: string;
    };
    query?: never;
    url: '/api/workflow/tasks/{taskUuid}/reject';
};

export type RejectWorkflowTaskResponses = {
    200: ApiResponseValue;
};

export type RejectWorkflowTaskResponse = RejectWorkflowTaskResponses[keyof RejectWorkflowTaskResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthCheckResponses = {
    /**
     * Successful response
     */
    200: unknown;
};
